exercism/exercism

- lib/app/presenters/workload.rb
- lib/app/routes/core.rb
- lib/app/routes/exercises.rb
- lib/app/views/nitpick/index.erb
- lib/app/views/nitpick/pending.erb
- lib/exercism/guest.rb
- test/app/submissions_test.rb
Closes #1952
Related to (but does not close) #2125
Allow unauthenticated guests to view all the iterations of code and all
the nitpicks others have left on the submission page.
Allow unauthenticated guests to see a lot of links on the submission
page, to give them an idea of what they could do if they signed up.
Most of these links lead to a "you have to be logged in to do that"
page.
Show nitpick index page header and nav links even if no submissions are present
in list.  This improves the UX of that page a little and makes `NullWorkload` simpler.
This is what a submission page looks like now to an unauthenticated guest:
--------
This is what the nitpick index page used to look like for someone who hadn't done exercises / nitpicked in that language:
--------
And this is what it looks …
> Allow unauthenticated guests to view a submission

- config.ru
Even though the setup instructions explain how to set the environment variables, it turns out there was never any place in the code that actually read the `.env` file.
> load variables from .env file

- lib/app/routes/exercises.rb
- lib/app/routes/github_callback.rb
- test/app/submissions_test.rb
It happens because the github callback makes a GET request, and this path responds to POST (since we were trying to post a nitpick - note that `POST /submissions/:key/nitpick` was our last action before the app requires login)
I noticed, a few weeks ago, that it also happens when trying to like/unlike or mute/unmute a submission when you are not logged in or the session is expired.
To solve this, I implemented the missing GET routes and made a redirect to the submission page (https://github.com/josuelima/exercism.io/compare/exercism:master...master#diff-9a49b3ebc7cdcea3905de6879bfff474R69)
I've also made a small change in the redirect at github callback (https://github.com/josuelima/exercism.io/commit/54e88ffb8fadd81439a29ebc911836b60d90a2ec#diff-e52ecb093dfc858532ef2f30c5f7e476R25). It …
> Fixes #2154 (404 after logging in with github)

- frontend/app/js/controllers/markdown_controller.coffee
- frontend/spec/controllers/markdown_controller_spec.coffee
- lib/api/routes/users.rb
- lib/app/public/js/app.js
- lib/app/views/submissions/comment.erb
- lib/app/views/submissions/submit_comment.erb
- lib/exercism.rb
- lib/exercism/user_lookup.rb
- test/api/users_test.rb
Closes #1805
When given a submission_id, order commenters higher than non-commenters
Match only by beginning of username, rather than anywhere in username
Change user lookup http request from POST to GET
All else being equal, sort alphabetically by username
At least two things I'm unsure of:
1. If passing the `submission_id` as I'm doing it (with the `data-sumission-id` attribute on an html element, and then looking it up in the DOM using Javascript) is the correct way of getting that info for the http request.
2. If it's ok to expose the `submission_id` in the html of the page delivered to the client, or if I should instead change it to use the `submission_key`.
> Sort participating users higher in user lookup

- lib/app/views/submissions/edit_nit.erb
- test/acceptance/nits_test.rb
I was receiving an exception while trying to navigate to the edit nit page:
```
NameError - undefined local variable or method `submission' for #<ExercismWeb::Routes::Comments:0x007f59ff806a28>
```
`submissions/comment.erb` is calling `submissions` but was not receiving it as a local.
> Pass submission to 'submissions/comment' erb

- lib/app/views/site/about.erb
These were already listed in the "Exercises are currently available in: " section, so I removed them being duplicated in the "Coming Up:" section. Just wanted it to be a little more clear.
> Remove already supported "Coming Up" Languages

- lib/app/views/application/footer/social.erb
GitHub link on footer didn't match the GitHub case used across the rest of the site.
> Updated GitHub link text in footer

- README.md
Doesn't seem like ```sudo``` is necessary for installing Lineman, but correct me if I'm wrong.
> Updated Lineman setup

- lib/services/email/notifications.erb
- lib/services/email/notifications.html.erb
- lib/services/notification_message.rb
Took a stab at adding the notifications link to notification emails.  Appears to be working correctly in MailCatcher.
> Updated notifications email. Fixes #2209

- lib/app/routes/teams.rb
- lib/exercism/team.rb
- lib/exercism/user.rb
- test/exercism/user_test.rb
Whenever we add someone to a team we make sure that they exist if they don't we create them.
Fixes #2124
> Add users that haven't signed in to team

- lib/app/views/account/show.erb
Fixes #2226 
Current iteration info of each exercise is shown on accounts page.
The column name `Iterations` seemed to denote total number of
iterations. Change it to `Current Iteration`.
> Change column name 'Iterations' to 'Current Iteration' on accounts page.

- lib/exercism/submission.rb
- lib/exercism/use_cases/creates_comment.rb
- lib/exercism/user_exercise.rb
- test/exercism/use_cases/creates_comment_test.rb
Whenever we comment on a hibernating `Submission` we must also make sure that we change `UserExercise`'s state too. Previously, `UserExercise`'s state stayed as hibernating which is why users were seeing alerts despite commenting.  
Fixes #2179
> Change user exercise's state when someone comments

- frontend/app/js/script.js
- lib/app/public/js/app.js
Fixes the issue where the submit button isn’t disabled when the user submits a nit using `cmd/ctrl + enter` the submit button will be disabled.
It also fixes the user being able to send `cmd/ctrl + enter` multiple times which would send multiple comments with the same body.
I only changed the Javascript under `lib/app/public` and not under `/frontend`. Should I add it there as well or is `/frontend` only for style development?
closes #2221
> Fix for double posting comments with ⌘+Enter

- lib/api/routes/iterations.rb
- test/api/iterations_test.rb
While implementing https://github.com/exercism/cli/issues/73 I ran into this issue. Let me know if this is how we want to handle attempts to skipping invalid exercises. 
Skipping an already started or skipped exercises would cause an exception due to an unique index on the `UserExercise` fields. We only want to skip exercises that have not been attempted or skipped
> Only skipped new exercises.

- lib/app/public/sass/base/components/beta_banner.scss
I find it hard to write a quick comment on my phone because the beta banner is hidding the nitpick form. I suggest hiding the banner on mobile.
> Don't display beta banner on mobile

- README.md
Three minor changes to the README’s [Prerequisites section](https://github.com/exercism/exercism.io#prerequisites):
* chruby is for Ruby switching, but for installing is ruby-install,
* the postgresql package always depends on the latest version,
* the postgresql-contrib package is needed for the citext extension.
> README: better prerequisites

- lib/db/connection.rb
- lib/tasks/db.rake
- lib/tasks/seed.rake
This makes the `db:setup`, `db:reset` and `db:seed` tasks actually work and use the values from `config/database.yml`.
This uses the host everywhere, so it works in default PostgreSQL configurations (which require peer identification on socket connections and only allow user/pass auth when connecting over the network). This also creates the PostgreSQL user with a password and then uses that password where needed.
This also uses `Kernel#system` – rather than <code>Kernel#`</code> – as the former does proper shell escaping.
I don’t like how the config values are obtained here (and that `DB::Connection.establish` violates CQRS), but getting the config from an existing `DB::Connection` was simpler than instantiating a `DB::Config` with the right environment. In the long run I think it should …
> Working db setup tasks

- lib/app/helpers/submissions_helper.rb
- lib/app/views/submissions/nit.erb
- lib/app/views/submissions/toolbar.erb
- lib/exercism/submission.rb
- test/exercism/submission_test.rb
I have a suggestion that I think will increase the incentive to nitpick: **provide a link to a nitpicker's submission below their comment.** This way, people are more likely to nitpick their nitpicker's code!
This also adds a link to a user's own submission for a problem they are viewing. I find myself often wanting to review my own code after looking at someone's implementation but it's too many clicks away.
I added tests for Submission#participant_submissions. That method avoids N queries when there are N comments. Please check that it will correctly return the latest submission for each user. I used `where.not(state: 'superseded')` for that condition.
> Link to my submission

- lib/db/config.rb
- lib/db/connection.rb
- test/db/config_test.rb
This moves environment handling from `DB::Connection` to `DB::Config` as per https://github.com/exercism/exercism.io/pull/2246#issuecomment-84512331 (and cleans both a bit along the way).
> Move env handling from DB::Connection to DB::Config

- Gemfile
- Gemfile.lock
- README.md
- lib/db/config.rb
- lib/db/connection.rb
- lib/tasks/db.rake
- lib/tasks/seed.rake
- test/db/config_test.rb
This makes the `rake db` tasks a bit better:
* exposes `DB::Config#database`, `#host`, `#password` and `#username` (and uses them in tasks),
* adds `rake db:from_scratch` that sets up the development database in one go.
This also installs the mailcatcher gem in development and adjusts the README accordingly.
> Better rake db tasks and setup instructions

- lib/app/helpers/site_title_helper.rb
The method seems to be returning the string "exercism.io" when no value was passed to it explicitly, and return the passed value itself when one is passed.
> Minor refactor of site_title_helper

- lib/api/routes/iterations.rb
- test/api/iterations_test.rb
This should solve #2239. System now checks if the issue exists before allowing the user to skip it. It returns 404 and error message if the issue doesn't exist.
I also noticed missing test case for when guest user is trying to skip the issue, so I added it and I moved things around a bit for better readability (introduced some variables, split longer lines etc.).
Ideally I would continue and refactor `api/iterations_test.rb` and maybe `iterations.rb` itself. Any thoughts on this?
> Disallow skipping non existent problems

- lib/app/helpers/markdown.rb
- lib/exercism/markdown.rb
Just quick fix of syntax highlighting for Objective-C. See #2275.
> Fixed syntax highlighting for Objective-C

- lib/tasks/db.rake
Just a little fix: I've noticed `db:reset` rake task had 'config.user` instead of correct `config.username` as an argument. Plus small clean up.
BTW Any reason why we are not using default database tasks from active record?
> Fix rake db reset task

- README.md
Not terribly important, but probably would be nice to have correct path in the README. Re: #2292
> Fixed path to Compass config in README

- lib/app/views/application/footer/social.erb
Seems like this is missing from the footer, but maybe there's a reason it was left off.
> Add Twitter link to footer

- lib/app/views/application/_footer.erb
ooops, I accidentally pushed the version with old front end scripts commented out and new included. It's suppose to be the other way around for now.
> Quick fix wrong JS included

- lib/app/views/account/show.erb
Right now, "Create a new team." occurs as:
I have added some space before it:
The <p/> tag seems fine for now. I tried with the <br/> tag but it was adding a bit more space than needed.
> Give some space for the new paragraph

- lib/app/views/account/show.erb
I have attempted to organize content on the accounts page using navigation pills and tabs.
This:
shall now look like:
I have included the content not under 'Teams' or 'Exercises' under 'Settings'.
Let me know in case there is a need for an issue for the same :)
> Organize content on account page using navigation pills

- lib/app/views/submissions/feedback_guide.erb
Because the entire alert had a data-dismiss tag it didn't receive the link click for the Read more link.
This fixes #2298.
> Fix read more link in Feedback Guide alert

- lib/app/views/account/show.erb
- lib/app/views/user/_exercises_table.erb
- lib/app/views/user/show.erb
We used similar (but not the same) table for listing exercises in 3 places. This consolidates it to one. Should also make #2354 easier to implement.
> Extract exercises table

- .gitignore
Since database.example.yml exists, prevent users from committing database.yml.
> adding database.yml to .gitignore

- db/migrate/0_initial_schema.rb
- db/migrate/201404202208_create_looks.rb
- db/migrate/201407041409_create_lifecycle_events.rb
- db/migrate/201412161637_create_comment_threads.rb
Rails 5 will change the default from `null: true` to `null: false`.
Since some behavior might depend on the old default, add `null: true` to
all `timestamps` calls.
> Fix `timestamp` deprecation warning when migrating database

- lib/db/config.rb
- lib/tasks/db.rake
- lib/tasks/seed.rake
* The `system` method does not convert its args to Strings, but YAML loads the port as a Fixnum from the file. So we need to explicitly convert all db config values to strings before returning them.
* When importing seed data, we also need to use the configured port
> DB setup fixes

- lib/exercism/converts_markdown_to_html.rb
- test/exercism/markdown_test.rb
This adds a preprocessing step to the Markdown parser that adds new lines before and after code blocks to fix #2310
> fix new lines before and after code blocks in markdown, fix #2310

- db/migrate/201504251623_add_inviter_id_to_team_memberships.rb
- lib/app/helpers/notification_count.rb
- lib/app/presenters/inbox.rb
- lib/app/routes/teams.rb
- lib/app/views/notifications/index.erb
- lib/exercism/team.rb
- lib/exercism/team_membership.rb
- lib/exercism/user.rb
- test/acceptance/team_test.rb
- test/app/teams_test.rb
- test/exercism/cohort_test.rb
- test/exercism/team_test.rb
- test/exercism/user_test.rb
Proposal for https://github.com/exercism/exercism.io/issues/2340
* Refactor TeamMembership to store the inviter's id
* Remove use of Alerts for invitation notifications and creates notification message from unconfirmed team memberships
* Destroy dependent TeamMemberships if Team or User is deleted
* Add inline accept/decline buttons after notification
> Hide accepted invitation notification

- .rubocop.yml
- lib/exercism/markdown.rb
Make rubocop run clean. Disable Metrics/LineLength. See https://github.com/exercism/exercism.io/pull/2379.
> Silence all cops

- frontend/vendor/js/sortable.js
- lib/app/public/sass/application.scss
- lib/app/public/sass/vendor/sortable.sass
- lib/app/views/account/show.erb
- lib/app/views/user/_exercises_table.erb
- lib/app/views/user/show.erb
Adds a JS sorter for the `_exercises_table.erb` partial as described in https://github.com/exercism/exercism.io/issues/2354.  The table is sorted by 'Date Submitted' descending by default.  All columns are allowed to be sorted.
I have left the compiled JS/CSS/SCSS out of this PR, let me know if you would like me to include those.
> adding sortable js/css library to sort exercises tables

- lib/app/routes/exercises.rb
- lib/exercism/use_cases/hibernation.rb
- lib/tasks/alerts.rake
- test/app/exercises_test.rb
@kytrinyx this is a slightly different implementation that the one described in the issue https://github.com/exercism/exercism.io/issues/2359 but I think it will suit the system for the time being (Since you mentioned rebuilding the Alerts/etc)
The rake task `rake alerts:hibernation:convert_links` should only need to be run once, but is idempotent either way.
The old route is still in there, since there are probably other places that might be using it.  Let me know what you think.
> persist url to everlasting exercises link, that way the username can change

- lib/app/presenters/assignment.rb
- lib/app/routes/metadata.rb
- lib/app/views/exercises/readme.erb
- lib/app/views/exercises/test_suite.erb
- test/app/metadata_test.rb
- test/app/presenters/assignment_test.rb
- test/fixtures/assignments_multiple_files.json
Hi, I finally got around to finish my ROSSConf Vienna issue.
This PR
- adds an assignment presenter
- extracts all parsing logic from the metadata route (test files and readme)
- modifies test files view to show all test files
- adds tests
- adds Bootstrap tab bar to test files view and readme view to easily toggle between them
It fixes #2273 (and https://github.com/exercism/rossconf/issues/19 if it is still active)
> Show all test files for exercises, add tab bar

- lib/app/views/exercises/readme.erb
- lib/app/views/exercises/test_suite.erb
The readme and test suite URIs in the exercise page were being derived
from the problem name, so that for problems with multiple-word names
("Phone Number", "Nth Prime", ...), the URI was being assembled
incorrectly, causing an uncaught server error like this:
URI::InvalidURIError at /exercises/ruby/phone%20number
bad URI(is not URI?): /assignments/ruby/phone number
The fix is simply to use the `problem.slug` instead of the
`problem.name.downcase`.
Tests for this change produced noisy Xapi network output, so they
are not included in this commit. Two different testing strategies
are recorded in this Gist:
https://gist.github.com/amar47shah/0e73a5176fbba67fb398
> Assemble readme and test suite URIs from slug

- lib/db/connection.rb
- lib/tasks/db.rake
This is a fix for #2423 that’s an alternative to #2434 – `DB::Connection.establish` is harmless until Active Record tries to actually use it, so this simply switches the user existence check to a raw `psql` call.
This also escapes the username and password strings passed to raw SQL.
> Fix #2423 via a working db:setup and escape strings passed to raw SQL

- lib/app/views/application/_nav.erb
The link [Welcome new users](http://exercism.io/getting-started) in the navbar seems unnecessary for users who have been using exercism for a considerable amount of time now. So I think we can remove it for `onboarded users`.
Makes navbar cleaner.
> Remove the link for "Welcome new users" for onboarded users.

- lib/app/routes/exercises.rb
- lib/app/views/submissions/user_actions.erb
Fixes #2415, Allows users to put submissions into hibernation.
This PR, addresses hibernating the exercise, to re-open the process is still the same (comment, or submit new iteration).  
Not sure if it makes sense to add a "un-hibernate" <--- (insert hibernate antonym here) to the message dropdown for hibernated submissions?  If so, just let me know.
> Add hibernate option to submission menu

- lib/app/routes/exercises.rb
- lib/app/views/submissions/alerts.erb
- lib/app/views/submissions/user_actions.erb
After adding the hibernate option to a submission, the only way to
awaken was via comment or submitting a new new iteration.
Users can now select "wake up" from the manage dropdown to reset
exercise state back to 'pending'.
Also, not sure if this is exactly what was in mind.  If there is wording or anything you want me to change, just let me know, that's definitely not my strong suit. Thanks!
> Added option to wake up hibernating submissions.

- CONTRIBUTING.md
Update contribution guidelines to handle database configuration errors such as "PG::Connection" and "Peer authentication failed for user ..." issues. There was a bug with how the the `rake db:from_scratch` and `rake db:setup` were pulling from the database.yml file (the simply were not pulling the database.yml configurations), I found an alternative way around this bug to handle the database creation. 
Additionally I added a section for handling running exercism.io from within a Vagrant environment. Foreman does not work in a Vagrant environment due to the inability to specify a host address `0.0.0.0` to handle Vagrant's loopback issues. Instead Shotgun will have to be used to handle the requests because of its ability to specify the proper host address. 
Both features have been tested …
> Contributor guidelines updates

- .gitignore
- CONTRIBUTING.md
- Procfile_Vagrant.example
Figured out a more appropriate and efficient way of getting the server running in a Vagrant environment. While Foreman doesn't support explicitly stating a host loopback address, puma does. In the changes I have added a Procfile for Vagrant that reflects the needs of Vagrant. Instead of running `foreman s -p 4567` people with a Vagrant environment will need to run `foremans s -f Procfile_Vagrant` and if they need to adjust their port they can edit the Vagrant Procfile. 
The other question is should I add a `Procfile_Vagrant.example` file and then gitignore `Procfile_Vagrant` in the case of people changing port numbers and then submitting a pull request which would result in a change in the files. It seems like a better approach.
> Add Procfile_Vagrant and update CONTRIBUTOR.md to reflect the changes

- frontend/app/js/app.coffee
- lib/app/public/js/app.js
- lib/app/routes/teams.rb
- lib/app/views/teams/manage.erb
- lib/app/views/teams/member_submissions.erb
- lib/app/views/teams/show.erb
- test/app/teams_test.rb
- Update look of management tools
- Link to user/manager profiles to make sure you are acting on the correct person
- Delete button for users is text X rather than font-awesome as it was slowing page load and 'Delete' or 'Remove' text could be cumbersome for many users.
- Add `/teams/:slug/manage` route
- Update teams tests to match new route
- Update existing routes to stay on manage page when managing
Addresses #2491
> Move team management tools to separate page

- lib/app/views/teams/show.erb
The displayed team size did not count all members. It now does.
> Fix displayed number of team members

- db/migrate/201509141447_add_fetched_at_to_exercises.rb
- lib/api/routes/exercises.rb
- lib/api/routes/iterations.rb
- lib/app/presenters/dashboard.rb
- lib/app/views/dashboard.erb
- lib/exercism/user_exercise.rb
- test/api/iterations_test.rb
This enables Exercism.io to store and retrieve a list of exercises that the user has fetched but not submitted. In order for this feature to work, x-api must be modified to post a fetch for a new exercise in addition to getting the user's existing exercises.
One caveat: the fetch LifecycleEvent has been moved from `GET /exercises` to the new `POST /exercises/:language/:slug/fetch` route. Until x-api uses this route, the fetch events won't be created. If this is critical, then this change should not be deployed without the corresponding change to x-api.
Changes:
* Migrate `user_exercises` to add `fetched_at` timestamp
* Add route to register exercise as fetched
* Create 'fetch' LifecycleEvent in fetch route instead of in `GET /exercises`
* Exclude skipped and unsubmitted exercises from …
> Track fetched but unsubmitted exercises

- lib/app/views/notifications/index.erb
Language names are now used instead of capitalized track ids.
> Fix display of language names in notifications

- lib/app/views/onboarding/pay_it_forward.erb
The language in "Pay It Forward" was outdated and confusing since it directed new users to a "Nitpick" menu which no longer exists.
> Update language in onboarding to reflect new exercises menu

- lib/app/presenters/problems.rb
- test/app/presenters/problems_test.rb
This PR fixes issue https://github.com/exercism/exercism.io/issues/2577 (List exercises on language page in the track order), by using the new `/tracks/:id/problems` endpoint in the API... that just got deployed!  :-)  It also removes a test that is no longer applicable; it was testing that the _site_ filtered out the problems from other tracks, and that is now done on the _API_ side.
BTW, a big chunk of the change is merely indentation; to ignore such changes, use https://github.com/exercism/exercism.io/pull/2586/files?w=1 .
> fix exercise order on track page

- lib/app/public/sass/base/components/main.scss
A class has been added to `lib/app/public/sass/base/components/main.scss`. The `lib/app/public/css/application.css` file should be regenerated to include new classes in SCSS files.
I don't know if it is done in the deployment process. If not, I haven't configured a development environment for this repo, so it would take me a while to configure it and generate the `application.css` file. If it's easy, like running some `rake` task, I could try.
Fixes #2596
> Include a CSS class to show a background image for ECMAScript

- lib/app/views/onboarding/have_a_conversation.erb
This is my first time contributing to an open source project so I hope I'm doing it right!
Anyway, this is my fix for <a href="https://github.com/exercism/exercism.io/issues/2410">Issue #2410</a> where someone was having trouble marking their exercise as complete. I know that you've now moved on to archiving exercises instead so I've just added a paragraph to the 'have a conversation' page explaining how to do this. 
I hope this is the correct place for such an explanation. My first thought was to add a step to the onboarding process explaining how to archive exercises instead but since this is my first time contributing I went the simpler route. Let me know if this is not okay!
> Issue #2410 - Mark exercises as complete

- lib/api.rb
- lib/api/routes.rb
- lib/api/routes/tracks.rb
- lib/exercism/homework.rb
- test/exercism/homework_test.rb
This adds a very rough, but working, implementation of the endpoint that goes with the new CLI command `exercism status $language`. I wanted to submit this now it its very rough form before I start to refactor to make sure this is generally on the right path and that the logic is in the right place. I also need to write tests for this endpoint, but since I haven't use MiniTest before, that will have to come a little later.
> Adding API endpoint for `exercism status $language` CLI command

- lib/app/views/languages/languages.erb
- lib/app/views/onboarding/install_cli.erb
Issue #: #2604
This adds the instructions on each language page and removes the instruction shown in the onboarding flow which lets the user download the first problem for all languages.
> Add instructions to show user how to download their first exercise

- lib/tasks/db.rake
This removes the redundant `rake db:migrate` call within the `rake db:from_scratch` call. `rake db:from_scratch` calls the `rake db:seed` command which calls `rake db:migrate`.
This also fixes the failing `rake db:from_scratch` command (#2606) because the `rake db:migrate` call before running `rake db:seed` doesn't close the connection until the process is ended. As to why that is the case, I have no idea.
> Remove redundant rake db:migrate call within rake db:from_scratch

- lib/app/views/teams/member_submissions.erb
- test/acceptance/account_test.rb
If i fetch an exercise it shows up under my name on my team page even if I'm not intending to complete it. If I `exercism fetch` it fetches an exercise from every available track so to my team members it looks like I'm doing "Hello World" in several languages.
In addition to this being slightly misleading there is an extra weirdness if one of my team members who HAS completed that exercise clicks on it. They end up at the home page with a flash message "That submission no longer exists."
I changed the view to use the `current` scope instead of `by_activity` so it only shows exercises with 1 or more iteration. I also added a test to ensure this but I'm not sure how correct my test is for the domain. Let me know if this needs tweaked.
If this doesn't seem like the right solution I'd be …
> Only show exercises with iterations on the team member submissions page

- lib/app/views/dashboard.erb
Adds a link to the dashboard to the x-api CONTRIBUTING guide. Also attempts to improve the copy a bit, not sure how successful it has been ;)
I took the liberty of not adding the link above "Improvements" despite the suggestion in the issue. I couldn't find a decent way of adding it there, and I figured asking people to help with ideas/suggestions and asking them to help with code/problems are pretty much in the same vein.
Fixes #2213
> Encourage people to contribute

- lib/app/presenters.rb
- lib/app/presenters/tracks.rb
- lib/app/routes/languages.rb
- lib/app/views/languages/_getting_started.erb
- lib/app/views/languages/_having_issues.erb
- lib/app/views/languages/languages.erb
- test/app/presenters/tracks_test.rb
Issue: #2620 
@kytrinyx I added the repo url to language page, I added the link in the `_getting_started` partial that way both `_languages` and `_first_problem` will display the link.
At first I thought of wrapping the logic of fetching the repository url in a new `Presenter` like `Presenters::Repo`, but that would imply an extra request, so I placed in the inside the `Presenters::Tracks`, if you prefer to have it own presenter I don't mind change it back.
Last thing I didn't know if you wanted any kind of text so I placed the first thing it came to my head.
Waiting on your feedback
> Added repository url for language page

- app/views/user/_exercises_table.erb
The default sort column on the user show page is by "latest iteration."
The iteration date was displaying correctly, but the sorting was by
exercise creation_date, which coincides with the first submitted
iteration.
Addresses issue #2638
> Change to sort exercises by updated_at instead of created_at

- lib/exercism/trending.rb
Before looking at https://github.com/exercism/exercism.io/issues/2631 I was trying to get all tests to pass and I got a single failure:
```
$ RACK_ENV=test CI=1 bundle exec ruby test/exercism/trending_test.rb 
Run options: --seed 1136
F
Fabulous run in 0.083306s, 12.0039 runs/s, 12.0039 assertions/s.
1) Failure:
TrendingTest#test_trending_only_returns_recent_activity [test/exercism/trending_test.rb:24]:
--- expected
+++ actual
@@ -1 +1 @@
-["b57f5e6f0d1c49bb9f747beacd30362e", "ce2318e4ae5d40538f25649e6f0f98fd"]
+[]
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
ben@bang:~/sauce/exercism.io$ 
``` 
And it appears to be due to `Trending#for` comparing against local time instead of UTC. I am guessing I get this error because I am at GMT +1300. 
Also tried setting `created_at` values on …
> Ensure Trending#for uses UTC date comparison

- lib/exercism/syntax_highlighter.rb
- test/app/helpers/syntax_test.rb
Windows LF characters are ignored by the highlighter, resulting in strange formatting in the browser.
Closes #2629.
> Scrub LF from code before highlighting syntax

- app/views/site/about.erb
The `problems` directory in `x-api` has been renamed to `tracks`, breaking the link on the website.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/exercism/exercism.io/2652)
> Update about.erb for problems -> tracks rename

- app/views/submissions/edit_nit.erb
- frontend/app/js/script.js
- public/js/app.js
Issue: #2418 
By place the delete button inside the same form as the edit form, the javascript will change the flag `was_submitted` [js_file](https://github.com/exercism/exercism.io/blob/master/frontend/app/js/script.js#L44) to true disabling the pop up form happening.
What do you think abut this @kytrinyx and @trayo although if you try to refresh it will show a different pop up.
> Avoid showing pop up when deleting nitpick 

- lib/db/connection.rb
- lib/tasks/db.rake
I reported the problem on [Issue 2163](https://github.com/exercism/exercism.io/issues/2163#issuecomment-162811803): When a database isn't specified, postgres will try to use a _username_ database. The `setup` script can't specify the database because it hasn't been created yet. 
PostgreSQL provides the `postgres` database [expressly for this bootstrapping purpose](http://stackoverflow.com/a/2411860/106906).
I also added error-checking for the call to `Open3#capture3`.
> Fixes for bin/setup

- CONTRIBUTING.md
Hey :wave: 
I was going through the contributing document and found that the link for the curated issues was broken.
This PR fixes the link preserving the pre-selection of the start-here label.
Hope this is ok.
Thanks,
.FxN
> Fixed todo start-here link in contributing doc

- app.rb
When switching into device mode in Chrome, the session keys were being cleared. But using Rack::Session::Cookie instead of enable :sessions seems to fix this.
Resolves: #2492
> Use Rack::Session::Cookie instead of enable :sessions

- lib/exercism/iteration.rb
- lib/tasks/solution_path_cleanup.rake
- test/exercism/iteration_test.rb
- test/exercism/use_cases/attempt_test.rb
Fixes #2635 
Contains: 
* Fix to use filepath relative to the problem directory and not exercism root directory
* `rake` task to fix existing pathnames in the same way
> Store solution paths relative to problem and not root

- app/views/application/_nav.erb
- app/views/application/nav/five_a_day.erb
- db/migrate/201512072011_create_dailies.rb
- lib/exercism.rb
- lib/exercism/daily.rb
- lib/exercism/five_a_day_count.rb
- lib/exercism/guest.rb
- lib/exercism/user.rb
- test/exercism/daily_test.rb
- test/exercism/five_a_day_count_test.rb
- test/exercism/user_test.rb
This is based on
https://github.com/exercism/exercism.io/issues/2572#issuecomment-166112676
This does some small refactoring of the Five A Day feature.  It moves the SQL for the Five A Day into a view called dailies and places a Daily model on top of it,  this allows for true AR relations/queries, (i.e user.dailies).
In addition when a user likes a submission it will be removed from their suggestions, but not count toward their daily count.
@kytrinyx Please take a look and let me know what you think, and if I missed anything!
> Add dailies migration, AR relations, tests

- db/migrate/201512272120_create_dailies.rb
@kytrinyx changed the NOT IN to a JOIN, should allow postgres to more efficiently use indexes.  Did an EXPLAIN when from 10k cost to 750.
BEFORE: http://explain.depesz.com/s/4NU
AFTER: http://explain.depesz.com/s/cGtO
Let me know how it works against production, Ill rebase the other branch if it works.
Thanks!
> Move NOT IN to JOIN

- public/sass/base/components/inbox.scss
The counter is given a little more space and it does not appear in the upper left corner of the exercises list.
Before:
After:
> Center new element count in exercises inbox

- db/migrate/201512292315_add_track_mentor_to_user.rb
- lib/exercism/user.rb
- lib/tasks/data.rake
Related to #2501 
Migrations for steps 1, 2 and 3:
>1. Create a migration that creates a new column on users called track_mentor that nothing references.
2. Create a data migration (lib/tasks/data.rake) to copy data from users.mastery to users.track_mentor
3. Deploy and run db migration and data migration.
@kytrinyx , let me know what you think and if these changes make sense for these first few steps.
> Add track mentor on user and data task for migration

- app/views/languages/language.erb
I noticed when going through the exercises list it was sometimes difficult to select the caret to expand the section.  Added a button within the header to make expanding a section easy.
> Made collapsable toggles easier to select on exercises list

- app/views/site/cli.erb
Currently the PR Help section on the [cli page](http://exercism.io/cli) is not aligned with the tab.
This PR aligns it with the tab and also adds direct github links to the two filenames `./x/docs/cli.rb` and `./app/views/site/cli.erb`.
> Align the PR help section inside tab and add links to filenames

- app/views/languages/language.erb
- test/acceptance/static_page_test.rb
Adds a link to the cli on the language.  This way a user who has not installed the cli can easily find out how to as opposed to having to find link in footer or elsewhere
> Adds link to cli on language page

- app/views/user/show.erb
- lib/exercism/user_exercise.rb
- test/exercism/user_exercise_test.rb
This PR fixes https://github.com/exercism/exercism.io/issues/2693 by updating the named scope UserExercise#current to order by language and id ascending.  It also adds the corresponding test.
It also updates user/show.erb to use the current scope to maintain consistency and make this view much more readable as well.
> [Fixes #2693] - orders current_exercises by language, id

- Gemfile
- Gemfile.lock
Puma now allows installation with optional SSL if it is not found in cases like El Capitan.
> Update puma for openSSL fixes.

- db/migrate/201512311928_delete_mastery_on_user.rb
- lib/exercism/user.rb
- test/app/helpers/submission_test.rb
- test/app/submissions_test.rb
- test/app/teams_test.rb
- test/exercism/inbox_test.rb
- test/exercism/user_track_test.rb
Related to #2501 
Code changes and migration for steps 4, 5 and 6:
>4) Change the codebase to reference the users.track_mentor column instead of mastery.
5) Create a migration to drop the mastery field.
6) Deploy and run the db migration
@kytrinyx , could you take a look at this? I also refactored a task in `lib/tasks/data.rake` called `migrate mentor acls` to reference `track_mentor` instead of `mastery`. I'm guessing this is the task to open up access to track members?
Happy new year!! Time to go watch fireworks :tada:
> Refactor tests to use track_mentor over mastery and drop mastery from user

- app/views/languages/language.erb
> Add syntax highlight for exercism fetch command in language tracks

- app/routes/submissions.rb
- lib/exercism/user_exercise.rb
- test/app/submissions_test.rb
- test/exercism/user_exercise_test.rb
fixes issue #2716
The issue is that the dashboard queries user_exercises using the 'current' scope.  This scope looks for user_exercises where iteration_count > 0.  However the submissions delete route wasn't decrementing the submission.user_exercise iteration_count so although the submission was deleted the user_exercise would still be returned in the query.
Only spec I'm having trouble with is the request spec, have it working in browser but can't seem to get submission.user_exercise to update in the spec.  Am I supposed to be using the Hack::UpdatesUserExercise as in the other tests in test/submission_test.rb
> [FIXES #2716]decrements iteration count of submissions user_exercise

- app/views/account/show.erb
The [accounts page](http://exercism.io/account) has an extra `<a>` tag [here](https://github.com/exercism/exercism.io/blob/master/app/views/account/show.erb#L6) which messes up the next Avatar section. This PR fixes it, adds an API Key header and makes the page look like this:
> Tidy up the accounts page and add an API key header

- lib/exercism/user_progression.rb
- test/acceptance/profile_test.rb
- test/exercism/user_progression_test.rb
I was confused by the data model in my previous pr. I didn't realize that there could be exercises without iterations.
> Changes user progress to only show tracks submitted to

- app/presenters/profile.rb
- app/routes/account.rb
- app/views/account/_track_mentor_invite.erb
- app/views/account/show.erb
- app/views/user/show.erb
- test/app/account_test.rb
Related to larger story/issue #2501 
@kytrinyx 
I don't really expect a merge here. Just looking for some feedback and to see if I'm on the right track. And I'd love to write some unit and capybara tests (for good measure and just for practice).
Also, I know we talked about tying into notifications/inbox to alert the user of track mentor invitations and I also was thinking about that rake task that you had to unlock all exercises in the newly mentored track. Also maybe another endpoint for removing a users track mentor status (although I doubt that would happen).
Here are some examples:
**Before:**
**After:**
> Rough draft - UI for track mentor

- app.rb
- app/presenters/profile.rb
- app/routes.rb
- app/routes/account.rb
- app/routes/profile.rb
- app/views/account/show.erb
- db/migrate/201601271354_add_share_key_to_users.rb
- lib/exercism/user.rb
- test/app/presenters/profile_test.rb
- test/exercism/user_test.rb
Fixes #2731 
- Registered a new route class `Profile`
- Added an option to `profile` presenter in order to detect whether `guest/current_user` should be given access to `user's exercise`
> Add a profile share link

- app/helpers/user_progress_bar.rb
- app/presenters/profile.rb
- app/views/user/_exercise_progress.erb
- app/views/user/show.erb
- lib/exercism/user_progression.rb
- test/app/helpers/user_progress_bar_test.rb
- test/exercism/user_progression_test.rb
- sorts languages by the last time they were updated
- adds a more/less option for the user_progress page
- cleaned up the test suite to match minitest standards
> Have user_progress return a more descriptive hash

- x/docs/track.rb
Fixes #2784 
@petertseng, how does this look?
No astericks:
> Join language docs and 'better' boilerplate with newline

- app/presenters/profile.rb
- app/views/user/_archived_exercises_table.erb
- app/views/user/_exercises_table.erb
Fix for #2748
One exercise:
Multiple exercises:
@kytrinyx , thoughts?
> Archived exercises layout fix

- Gemfile
- Gemfile.lock
New app installations require rake 10.5.0. However, that version was not
specified in the Gemfile. This throws an error during 'bin/setup'
installation and having to install it manually. I had version 10.4.0 and I kept getting the error trying to setup the app to run locally. After I got the error I had to use the 'Troubleshooting' part of the guide to finalize the setup manually. With this rake version request, the full setup should run automatically as explained in the guides.
> Add required rake version in Gemfile

- lib/exercism/assumable_user.rb
I think it would be much more helpful to order assumable_users by username.  A lot of the time if I'm trying to find some users with data matching something I'm trying to test/look for I'll get a username and then assume the user that way.  Would be much easier to find the user by username rather than created at.
example.  I was working on fixing issue to list a user's team names on profile.  First I need to find a user with multiple teams.
User.joins(:teams)... find username.  Now assume that user's identity by username.
> orders assumable_users by username asc to make easier to find

- app/views/user/show.erb
This PR addresses first part of #2766, displaying user teams on profile page.  Team names will be displayed as links, which link to the team's page.  Not sure if want unconfirmed teams as well, but for now just using the existing teams method on profile presenter.  Let me know what you think, thanks
> displays user teams on profile page

- app/views/user/show.erb
This is a fix for the User's account profile page view: Use `team.slug` instead of `team.name` for team link on a user's profile page. 
The current `team.name` breaks for teams with multiple word names, like 'DTLA Pair Programming.' Instead of linking to http://exercism.io/teams/dtla-pair-programming/, it currently links to: http://exercism.io/teams/DTLA, which is a broken link. This commit will fix this bug.
What the bug looks like right now:
> User profile page: Fix broken team link

- api/v1/routes/tracks.rb
- lib/exercism/xapi.rb
Return 404 along with "Track <id> not found." if status is requested for a language we don't support.
This change came about due to exercism/cli#298
> Api return error if track does not exist

- app/views/user/_exercises_table.erb
Potential fix for the following date sorting issue:
Here are two screenshots of sorting of Latest Iteration column of Current Exercises table as it appears on a user's profile page:
It currently treats dates as text and 11 is not sorted correctly with 6 and 8. I do wonder if `Sortable` module doesn't consider '0' to come before '1' in text form.
**Warning**: I have not yet been able to verify that this works, not much experience with JS.
My `bin/setup` fails with `Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 10.5.0. Prepending `bundle exec` to your command may solve this.`
Then if I try `bundle exec rake db:setup`, I get the following:
```
PG::ConnectionBad: could not connect to server: No such file or directory
Is the server running locally and …
```
> [WIP] Sort dates correctly

- app/views/notifications/index.erb
I decided to let Bootstrap handle this by using the right column
classes.
Fixes #2767.
> Fix unclickable "mark all as read" button on smaller screens

- app/views/dashboard.erb
"Leap (Python)by user" now appears as "Leap (Python) by user"
> Add space after language: Dashboard Recent Viewed

- app.rb
Closes #2821 
Not sure if this is the best place to require this gem... Might be better to track down the place it gets autoloaded (maybe in `app/routes.rb` when one route calls `erb :some_view`)...
> explicitly require tilt/erb to suppress non thread safe warning

- lib/exercism/user_exercise.rb
- lib/exercism/user_statistics.rb
- test/api/users_test.rb
The statistics endpoint currently returns user.exercises, which includes exercises with iteration counts of 0. Because of this, the returned data is incorrect as it lists all fetched exercises as completed.
By scoping into exercises.completed, a new scope added to user_exercises for this purpose, exercises with 0 iterations will be excluded and will show accurate completion data.
> Update statistic endpoint to reflect accurate data

- app/views/languages/language.erb
I think 30px suits better than the default 40px for the language page.
Do you guys think that `"#{track.language} #{track_icon(track.id, 30)}"` should be in a helper?
Please let me know what you think.
> closes #2819. Add track icon to lang pages.

- app/presenters/dashboard.rb
- app/views/dashboard.erb
One idea to fix #2737
@kytrinyx, thoughts?
Less:
More:
> Group unsubmitted exercises by language and in a collapsible

- app/views/dashboard.erb
Reading "Exercise name — 7 comments, 3 iterations" is a bit easier and more natural (for a westerner) than reading "Exercise name — 7 comments, iterations 3" 🙃
> Let the reader read the counts naturally from left to right

- app/views/teams/manage.erb
- test/acceptance/team_test.rb
This PR tweaks the Manage page of a team to do two things:
- Display the current user in the list of managers if they are one so
that they can see they are a manager, as well as remove themself as a
manager if there are other managers.
- If the current user is the only manager, a disabled removal button is
shown with a tooltip explaining that the user must add another manager
before they can remove themself as the last manager.
This change was made so that when a manager is trying to leave a team
they know they are a manager and that they must add a new manager before
removing themself as a manager.
This commit also adds an acceptance test for viewing the Manage page of
a team and asserting the current user is in the list, as well as that
there is a disabled remove button since that user …
> Update team manage to handle sole manager scenario

- .rubocop_todo.yml
- .travis.yml
- CONTRIBUTING.md
- Rakefile
- api/v1/routes/iterations.rb
- app/presenters/tracks.rb
- app/routes/account.rb
- app/routes/static.rb
- app/routes/stats.rb
- config.ru
- lib/db/config.rb
- lib/exercism/locale.rb
- lib/rouge/formatters/html_exercism.rb
- lib/tasks/coveralls.rake
- lib/tasks/rubocop.rake
- lib/tasks/test.rake
- scripts/console.rb
- test/active_record_helper.rb
- test/api/users_test.rb
- test/app/helpers/fuzzy_time_test.rb
- test/db/config_test.rb
- test/exercism/markdown_test.rb
- test/exercism/team_stream_test.rb
- x/docs/launch.rb
This PR adds a new rake task called `test:everything` that, as the name implies, tests everything. It runs all of the checks to ensure the code is 👌 💯 ✨  before a PR is submitted and merged.
Right now, that new task runs MiniTest, RuboCop, and Lineman Spec.
The commits in this PR get the app setup for this task and adjust RuboCop to make it happy since it was a little grumpy. 🚨 🚔 
See each commit for details.
Closes #2846
> Add test:everything rake task

- app/views/submissions/show.erb
This fixes #2859 based on the feedback from @kytrinyx and @jkrmr on the issue and on @juliatjoy's pull request #2869.
- Moved the link to other implementations to the top right (screenshot attached)
- Removed the section visible in archived pages, with links to other implementations.
> Link to relevant activity stream from submission page

- CONTRIBUTING.md
On contributing.md line 206. Changed from `RACK_ENV=test rake db:setup db:migrate` to `RACK_ENV=test bundle exec rake db:setup db:migrate`.
> Adds 'bundle exec' to RACK_ENV command in contributing.md 

- lib/exercism/user_exercise.rb
This gets RuboCop (and thus the builds) passing since this offense was
introduced before 10591be6d5de31a789fab0e5e0cebe15716b766c was merged.
-----
I noticed the build was failing after recent merges, so this fix should get CI
builds passing again.
Something worth exploring might be requiring Travis CI status checks and forcing
a branch to be up to date before it can be merged, [which GitHub introduced recently](https://github.com/blog/2051-protected-branches-and-required-status-checks).
> Fix sole RuboCop offense in Exercism::UserExercise

- app/helpers/fuzzy_time.rb
- test/app/helpers/fuzzy_time_test.rb
Returns a `span` instead of a link for FuzzyTime. This will allow for the tooltip to be inserted within other links.
Fixes #2886
> Return a `span` tag for the tooltip toggle

- app/views/stream/_main.erb
Fixes [#2903](https://github.com/exercism/exercism.io/issues/2903).
> Use singular version of "comment" as receiver of call to pluralize.

- lib/tasks/db.rake
While setting up the database locally. I kept running into an undefined method error originating from `db.rake` file:
```
NoMethodError: undefined method `success?' for nil:NilClass
/Users/#######/code/open-source_contrib/exercism.io/lib/tasks/db.rake:45:in `block (2 levels) in <top (required)>'
```
The error was 3 lines all similar to this:
```
fail "Failed to create database" unless $CHILD_STATUS.success?
```
`$CHILD_STATUS` was `nil` and therefore the error. In order to use the variable `$CHILD_STATUS`, you have to require the English Library in Ruby and that is all I did. I searched the rest of the project and found no reference to this global variable. The alternative would to have been replace all instances of `$CHILD_STATUS` with `$?`, but I prefer the more readable version. 
This …
> Require English library in db.rake for $CHILD_STATUS

- lib/exercism/user_statistics.rb
- test/api/users_test.rb
We added stats listing the following data points: total_comments_received, total_comments_received_from_others, total_comments_created, total_comments_given_to_others, days_since_last_comment_given, days_since_last_comment_received.
Additionally, we redesiged the json structure for the submission statistics. Now, the submission_statistics hash has a value which is a hash that has track_ids as keys.
@adriennedomingus
@adamhundley
> Add comment stats to user stats endpoint and redesign submission stats json

- CONTRIBUTING.md
- bin/setup
For some contributors, the bin/setup file causes errors because not every rake command is prepended with `bundle exec`. Added those in. Resolves issue #2900.  Please also merge PR #2899 for other setup issues. Let me know if I need to change anything in this PR!
> Prepends rake commands with bundle exec for set up

- app/views/dashboard.erb
- app/views/languages/_block.erb
- app/views/teams/directory.erb
I spotted “1 iterations” on my dashboard, so came here to fix it.
I then found a few other missed pluralizations in the templates, and fixed them while I was in there.
> Fix pluralization

- app/presenters/dashboard.rb
- app/views/dashboard.erb
- lib/exercism/comment.rb
- lib/exercism/excerpt.rb
- test/exercism/excerpt_test.rb
Fixes #2752. Based on the discussion on #2867, I have cleaned up the UI, and cut off the comments if the length exceeds 160 characters.
This is what the feedback section looks like now:
> Comments in dashboard feedback section

- app/views/user/_exercises_table.erb
I was finding myself going to the exercises table to see which ones I'd
completed, then clicking languages, finding the language I'm working on, then
clicking Available Exercises.
This adds a link to the existing Language name to the track. (Tried to deep link
to the exercises section i.e. `/languages/ruby#exercises`, but it looks like
the anchors aren't working onload?)
> Add a link from exercises table to track

- frontend/app/js/app.coffee
- public/js/app.js
The website doesn't set page titles so using the browser history is impossible. They all say 'exercism.io'. This change adds some Javascript to grab the first H1, H2, or H3 and use that to build the page title
setting it to the text value of the header plus " - exercism.io" -- but only if the page title isn't already set to something special.
> Set page titles using Javascript

- lib/exercism/markdown.rb
- test/exercism/markdown_test.rb
Fixes #2759 
Also closes out #2775 because using commonmarker required buildpacks and lots of other nonsense
Also removed `preprocess` because I wrote terrible terrible regex for that.
> Add lax spacing for better markdown list processing and better tests for lists

- app/views/site/about.erb
Add's a bit of background on the naming of Exercism.
In reference to https://github.com/exercism/exercism.io/issues/2940
> Add origin of exercism name to about page

- lib/exercism/team_stream_filters.rb
Fixes #2946 
Turns out [this assertion](https://github.com/exercism/exercism.io/blob/master/test/exercism/team_stream_filters_test.rb#L40) was failing in my local environment.
> Fix aggregated unread submission count in Team stream.

- CONTRIBUTING.md
- lib/tasks/seed.rake
As a follow up of the debugging that happened on #2949, it made sense to
document the seeding behaviour differences between local environment and
Heroku. Ideally seeding is intended to be run only on development machines, but
if it needs to be run on Heroku for testing out some feature or to demo it to
the core team, the current seed script needs to be modified. However,
because there is a chance that `db:seed` might be run by some plugin (or a
buildpack) in the setup pipeline, and we don't want it to happen on
production(😱), I've made it a separate task and documented accordingly.
- Add separate seeding task to be run on Heroku
- Add rudimentary documentation about seeding in CONTRIBUTING.md
> Add a separate seed task for Heroku seeding purposes

- app/views/teams/directory.erb
- app/views/teams/manage.erb
- app/views/teams/new.erb
- db/migrate/201606261414_add_description_to_team.rb
- lib/exercism/team.rb
- test/app/teams_test.rb
The motivation for this PR can be found [here](https://github.com/exercism/exercism.io/issues/2944).
For now I didn't try to come up with any design decisions and would love to receive suggestions regarding the current layout.
**User profile:**
**Team page with a team that has a description:**
**Team page with a team without a description:**
**Managing a team:**
> Add description field to Team.

- app/routes/teams.rb
Bug: Given an Exercism user in a very active team viewing a certain amount of problems on the teams/:slug/streams page, when the user clicks on a pagination link, the URL changes but the view does not. 
This pull request: In the routes file for this get request, we added the `params[:page]` from the URL into the TeamStream class initialization. 
LA Open Source Pair Programming Meetup: 
@jendiamond
@machikoyasuda 
Jake Wilkins
Ed Vernon
Jamie Mendoza
John S.
Cathy Hillman
Michael
@lenkli67
Anna 
Eric Stevens
Cristine Meinders
> Fix: Fix pagination error on team/:slug/streams URL.

- app/views/teams/manage.erb
- app/views/teams/new.erb
- db/migrate/201606291508_add_public_flag_to_team.rb
- lib/exercism/team.rb
- test/app/teams_test.rb
This PR was motivated by [this](https://github.com/exercism/exercism.io/issues/2944) discussion.
This flag will be useful when we implement the feature that allow an user to search for teams (only public teams will be returned).
Current layout:
* **Create:**
* **Update:**
> Add public flag to Team.

- app/views/site/about.erb
Most submissions don't include any kind of explicit license, so something like http://choosealicense.com/no-license/ would apply.  It's probably overkill to try and explain that here, as is requiring that all submissions are made under a default license like codingame.com does (requiring GPLv3).  However, what *is* important to note is that exercism.io is not trying to claim any ownership of these submissions.
/cc @gmlewis
> Clarify that submissions are owned by their author

- app/views/user/_exercises_table.erb
I added the number of comments to the exercises table on the user page. I would find this helpful for seeing at a glance which of my (or others') past exercises got a lot of feedback for reviewing after the fact.
> Add comments count to exercises table

- app/views/teams/manage.erb
- app/views/teams/new.erb
- db/migrate/201607131820_create_tags_table.rb
- db/migrate/201607131825_add_tags_to_team.rb
- lib/exercism.rb
- lib/exercism/tag.rb
- lib/exercism/team.rb
- test/app/teams_test.rb
- test/exercism/tag_test.rb
- test/exercism/team_test.rb
This PR was motivated by [this](https://github.com/exercism/exercism.io/issues/2944) discussion, this is the 3rd step in the roadmap.
With this we will have tags associated with a team, the next step will be adding a page to search for teams containing a specific tag.
The UI/UX is pretty simple for now, there is no javascript os CSS involved, but we can discuss if we want to style tags.
> Add tags for teams.

- x/docs/md/cli/mac.md
Fix anchor links to install exercism with Homebrew and without Homebrew on cli page
> Fix link navigation to install exercism on mac

- app/views/user/_exercises_table.erb
I think it is better to have the exercises sorted by the time of submission rather than
languages. With a lot of languages, old exercises show up at the top while latest submissions are somewhere below. Most recent submissions should be at the top.
Sorted by the last iteration timestamp in descending order (most recent first).
> Sort exerises by last iteration instead of language name

- app/routes/static.rb
- app/views/site/version.json.erb
- config/build_id.rb
- test/app/static_pages_test.rb
Add a '/version' route that returns a json string with information about the current build.
(This is similar to what is provided as default by http://x.exercism.io/)
Example:
```json
{"repository":"https://github.com/exercism/exercism.io","contributing":"https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md","build_id":"ef04547"}
```
In order for the app to display the current build an environment variable needs to be set on the server before running the app. One way to do this:
```bash
export BUILD_ID=$(git rev-parse --short HEAD)
```
> Add /version route that returns meta information

- CONTRIBUTING.md
Add some notes about live deployment.
* It's done periodically, 
* The current live version accessible via /version.
* There are Gitter /dev room notifications.
> Documentaion: CONTRIBUTING.md - add some notes about live deployment.

- lib/exercism/converts_markdown_to_html.rb
- test/exercism/converts_markdown_to_html_test.rb
- test/exercism/markdown_test.rb
Make markdown code blocks display the same in comments and in preview.
**Bug:** When trying to add a markdown code block to a comment on a solution the code block will show up correctly in the preview but not in the submitted comment.
**Cause:** The preview is submitted by JavaScript call and has "\n" line-breaks.
The real submit is handled by the browser using has "\r\n" line-breaks.
**Solution:** Update the code block regex to also accept "\r\n" line-breaks
Be more forgiving about what are valid characters at the end of code-block-closing backticks.
Other things this commit does:
Improves test coverage.
Adds tests for code in backticks surrounded by newlines.
Adds test coverage for convert class method.
Simplifies convert class method.
class ConvertsMarkdownToHtml now has 100% test …
> Fix markdown code block display in comments. (Fixes #2915)

- lib/exercism/syntax_highlighter.rb
See #2988
@verdammelt would you eyeball this and let me know if it looks right?
> Add syntax highlighting for lisp track

- lib/tasks/db.rake
`db:drop` command currently fails trying to log in with the existing
user (for me existing user is `tejas` while the db user is `exercism`).
There is no way to supply password to `createdb` and `dropdb`
commands. It prompts for password by default. Also using `-U` for user
instead of `-O` for owner.
> Add username and ask for password for `rake db:drop`

- app/views/stream/_main.erb
- lib/exercism/stream_exercise.rb
- lib/exercism/team_stream.rb
- lib/exercism/track_stream.rb
- lib/exercism/user_exercise.rb
- test/exercism/stream_exercise_test.rb
`help_requested` also needs to be implemented in track_stream due to the code duplication between track_stream and team_stream.
> Fix help request display on team stream. (fixes #3018)

- app/routes/core.rb
- lib/exercism/guest.rb
- test/exercism/guest_test.rb
The error handler was erroring if the user was not logged in because the Guest class did not have a `username` method.
Add `username` method to Guest.
100% unit test coverage of Guest
Also, `BUILD_ID` is now availiable as a constant so use that instead of the environment variable.
> Bugfix: Make core 500 error handler work for Guests (fixes #3002)

- CONTRIBUTING.md
I just went through the instruction to set up the app locally, and didn't have Postgres running, which of course gave me errors. To help others avoid confusion, I figured it would be good to mention that the DB needs to be running before executing the setup script.
Since it's a one line change in a markdown file, I didn't branch. I'll resubmit if you prefer I do it properly.
> Adds a note regarding running PostgreSQL in the background

- .gitignore
Local versions of Ruby gems can be installed in /vendor and should be ignored.
Some of the js assets live in frontend/vendor/js and need to be able to be checked in.
> Only (git)ignore root vendor path.

- .rubocop.yml
`node_modules` includes `lineman` which contains some Rakefiles that
Rubocop does not like. Since these are vendor provided we will not lint
them ourselves.
(This issue is not present during CI because the Rubocop scan is run
BEFORE the node modules are installed.)
> Exclude node_modules/* from Rubocop scan

- api/v1/routes/iterations.rb
- lib/exercism/iteration.rb
- test/api/iterations_test.rb
- test/exercism/iteration_test.rb
When using an old version of the CLI that does not submit the track id
as part of the data, Exercism tries to guess the track from the path of
the submitted filename.
However paths could come in with mixed case names and since all language
track_id's are lowercase track_id matching would fail.
This patch makes sure the deduced track_id is all lowercase.
This also required modification to the Iteration class due to
duplication of path parsing logic.
> Case insensitive solution paths (Fixes #2468)

- app/views/site/index.erb
closes #3038
adds link as suggested
[update]
before:
after:
> add link to newsletter archive on site index

- x/docs/md/help/executable.md
This is regarding Issue #3045 
I have added further documentation regarding the `exercism configure --dir` command. Please let me know if there are any corrections required :)
Also, what is the difference between \`\`\`bash\`\`\` and \`\`\`plain\`\`\`?
> Added documentation for --dir

- lib/exercism/syntax_highlighter.rb
- lib/rouge/formatters/html_exercism.rb
- test/exercism/converts_markdown_to_html_test.rb
- test/exercism/html_formatter_test.rb
- test/fixtures/approvals/markdown_double_braces.approved.txt
- test/fixtures/approvals/markdown_with_clojure_code.approved.txt
- test/fixtures/code_formatting/ocaml
- test/fixtures/code_formatting/python
- test/fixtures/code_formatting/swift
Replaces #3048 and #3058 after the first one was reverted in  #3056, addresses #3050 and the original #3044.
This changes the formatter to use Rouge's native `token_lines` method instead of roll-your-own, and removes many of its unused options; otherwise the behavior and code is similar to #3048. @Insti provided motivation to rewrite and trim the formatter, some nice refactors and adjusted tests.
> Simplify syntax highlighter and add support for multiline comments/tokens

- app/routes/languages.rb
- app/views/languages/index.erb
Currently, the Upcoming & Planned section languages come from an array
called inactive. Due to them being intermingled, it causes some issues
on the Languages index page in Planned.
This partitions the two out and simplifies the view page.
I'm happy to hear any recommendations on a better way to implement this. Also, if this is the way to go, then maybe `inactive` needs a new name since it's no longer accurate?
> Partition Inactive Languages to Inactive & Planned

- app/views/submissions/edit_nit.erb
- test/acceptance/nits_test.rb
When using the site this evening, I noticed that when I went to edit a comment, it had the old wording to edit a "Nitpick". This seems an artifact of the old naming, so here's a PR to change it and make things more consistent.
> change 'Edit Nitpick' to 'Edit Comment'

- app.rb
- app/helpers/notification_count.rb
- app/presenters/inbox.rb
- app/presenters/profile.rb
- app/routes.rb
- app/routes/invitations.rb
- app/routes/teams.rb
- app/views/account/show.erb
- app/views/dashboard.erb
- app/views/notifications/index.erb
- app/views/teams/directory.erb
- app/views/teams/list.erb
- app/views/teams/manage.erb
- db/migrate/201608152201_create_team_membership_invites_table.rb
- lib/exercism/team.rb
- lib/exercism/team_membership.rb
- lib/exercism/team_membership_invite.rb
- lib/exercism/user.rb
- lib/tasks/data.rake
- test/app/invitations_test.rb
- test/app/teams_test.rb
- test/exercism/team_membership_invite_test.rb
- test/exercism/team_test.rb
- test/exercism/user_test.rb
This change is part of a [bigger plan](https://github.com/exercism/exercism.io/issues/2944) that involves allowing users to request membership for a team.
Although this PR has several changes, it all boils down to use the new table/model instead of relying on the `confirmed` column of the `team_memberships` table.
> Change invite feature to rely on its own table

- app/views/submissions/submit_comment.erb
- frontend/app/js/app.coffee
- frontend/app/js/script.js
- public/js/app.js
Fixes #2957
I've successfully added the ability to save iteration specific comments to localstorage, but still need to figure out how to remove them after a successful form submission. I'll need to look more into Angular.
I'm also attempting to move the comment submission code into `frontend/app/js/app.coffee`. I imagine, that in the future, it'd be nice to break that JS code up into page specific portions. 
Since we'll be storing comments to localstorage, I believe we can remove the page exit confirmations...but perhaps it's worth it in case there's a JS race condition that doesn't save their comment or they have JS turned off.
> WIP refactor submissions js

- docs/reviewing-a-pull-request.md
This should help both contributors and maintainers provide a comprehensive review when pull requests are submitted to the individual language track repositories.
View the [rendered file](https://github.com/exercism/exercism.io/blob/docs-reviewing-a-pr/docs/reviewing-a-pull-request.md).
In particular, this focuses quite strongly on how to review a pull request that adds or changes an exercise.
@exercism/track-maintainers and in particular @IanWhitney @petertseng @ErikSchierboom @parkerl @devonestes @Insti @kotp @jtigger @matthewmorgan who I know review a ton of pull requests: _What have I missed?_
> Add documentation about reviewing pull requests on language tracks

- docs/maintaining-a-track.md
This is a high-level bit of philosophy, mostly, inspired by an email written by @parkerl.
View the [rendered document](https://github.com/exercism/exercism.io/blob/documentation/docs/maintaining-a-track.md).
I'd also like to add several other documents about specific, targeted tasks that we do as maintainers (or as contributors). I hope to break the [x-common contributing guide](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md) into smaller pieces that are more task-oriented. I think this will make it less overwhelming and easier to find the documentation we need.
Update: this should link to something like the document in #3105 in the tactical section at the bottom.
/cc @devonestes @parkerl because you were involved in the original conversation.
/cc …
> Add a document about maintaining a track

- lib/exercism/markdown.rb
- test/exercism/markdown_test.rb
- "options" are parameters for the Redcarpet renderer, while
"extensions" enable features in the parser.
- Remove duplicate test.
> Make headers in markdown linkable.

- app/routes/tracks.rb
- lib/exercism/track_stream.rb
- lib/exercism/track_stream_filters.rb
- test/exercism/track_stream_filters_test.rb
Currently on tracks, filters for language and language/problem exists and do not have option of filtering user's solutions/exercises.
This PR adds a filter on tracks where user can filter out only his/her solutions for a particular language track. The filtered results doesn't include archived exercises.
Below is the screen shot. 
Please let me know the feedback on this.
> Adds user filter on track stream

- CONTRIBUTING.md
@kytrinyx 
I have notice that the documentation for compiling the css to production is outdated.
for references [compass-production](http://compass-style.org/help/tutorials/production-css/)
> Update Compass instructions for compiling the csss to production

- app/views/languages/_repo.erb
- app/views/languages/repositories.erb
* Fixes https://github.com/exercism/exercism.io/issues/3101
* List of language track repositories are now in tabular format.
* Updated all the 3 sections: `Language tracks`, `In Progress` & `Planned`.
@kytrinyx please find below screenshots of Before/After fix.
- Before Fix (Lists in grid)
- After Fix (Lists in table)
> Make the list of language track repositories more scannable.

- api/v1/routes/iterations.rb
- api/v1/routes/tracks.rb
- lib/exercism/use_cases/attempt.rb
- lib/exercism/xapi.rb
- test/api/assignments_test.rb
- test/api/iterations_test.rb
- test/exercism/use_cases/attempt_test.rb
- test/x/exercise_test.rb
- x/exercise.rb
This closes #2637 and exercism/todo#167
> I think it would make sense to implement this as X::Exercise.exists?, which would rely on X::Xapi, which calls v3.
The following changes were made:
- Use `X::Exercise` for the Iterations class
- Use `X::Exercise` for the Tracks class
- Use `X::Exercise` for the Attempt class
- Migrate the `exists?` class from `X::Xapi` to `X::Exercise`
There was a small comment on the original implementation for this PR that I also wanted to address however I did not know (yet) on how to implement the test. I left a docstring comment on the test in hopes that somebody will be able to point me to the right direction 😄
> Replace calls to Xapi.exists? with call to x-api v3

- test/exercism/team_stream_filters_test.rb
- test/exercism/track_stream_filters_test.rb
- test/exercism/track_stream_test.rb
The tests for team streams, track streams, and the filters for both streams all had conflicting
class names, which means that they were reopening the same class. Since some tests had the same
name, some tests were not being run, which was hiding failures.
This fixes both the test names and the failures.
/cc @bernardoamc just for your information. I'm going to merge this so I can work on top of it.
> Fix overlapping test names

- x/docs/md/cli/mac.md
Was surprised that `\brew update` works, actually, but it's 
unnecessary and inconsistent with the rest of the page.
> fix minor formatting in Mac CLI readme

- Gemfile
- Gemfile.lock
- app/helpers/track_image.rb
- app/routes/tracks.rb
Earlier today I merged #3138 ... but I had totally forgotten that we also need to configure Exercism to actually serve the images from the new location. So all the track icons disappeared.
I rolled back the deploy.
This adds `trackler` as a dependency.
Trackler was extracted from exercism/x-api. It wraps all the basic Exercism data (x-common, the tracks, their implementations) into a single bundle, and has some wiring to make it easy to manage.
Then it
* adds an endpoint to serve the image and
* updates the view helper to reference the endpoint.
I've tested this locally:
> Serve images from the track repos

- app/views/user/_tracks_progress.erb
- app/views/user/show.erb
#3137
@kytrinyx, @NobbZ I just simply added a filter param, that let the user decide if he/she want to shoe more languages, just like in the old progress bar. Please tell me what you think.
Here are some examples:
Collapsed
Uncollapsed
> allow toggle languages progress to avoid overloading the profile page

- db/migrate/201610012033_create_watermarks.rb
This adds a database migration which we will need in order to add a _watermarks_ feature that will let us implement "mark all as read" in the activity streams with fewer rows in the database.
I'm adding the migration separately so that it can be run in production before we have any code that depends on it.
See #3130 for more details.
> Add migration for watermarks

- .rubocop_todo.yml
- db/migrate/201610012033_create_watermarks.rb
- lib/exercism.rb
- lib/exercism/problem.rb
- lib/exercism/team_stream.rb
- lib/exercism/team_stream_filters.rb
- lib/exercism/track_stream.rb
- lib/exercism/track_stream_filters.rb
- lib/exercism/watermark.rb
- test/exercism/team_stream_filters_test.rb
- test/exercism/team_stream_test.rb
- test/exercism/track_stream_filters_test.rb
- test/exercism/track_stream_test.rb
**Note: this is a follow-on pull request building on three separate PRs (#3141, #3142, and #3131) that should all be merged before this gets merged. This will make it easier to review, as it will contain significantly fewer changes.**
This ensures that the exercises in the stream itself get the correct read/unread status, and that the sidebar takes the watermark into account when displaying the unread counts.
See https://github.com/exercism/exercism.io/issues/3130
> Use watermarks to determine read/unread status

- lib/exercism/team_stream_filters.rb
- lib/exercism/track_stream_filters.rb
* Reorder the filters themselves, to be from the most general to the most specific.
* Reorder the parts of the SQL queries so that they're consistent within each filter
* Count exercises not views in the views SQL, since in a heartbeat we'll be introducing
watermarks, which won't have views to count on. This will let us stay consistent.
> Refactor stream filters

- lib/exercism/view.rb
- lib/tasks/views.rake
- test/exercism/view_test.rb
This is a continuation of the work in #3130
We have watermarks that we're using to set the read/unread state in the activity streams. We also use views, which are recorded individually when you visit a solution.
Watermarks are much more economical—you have one single watermark for all the solutions for a given exercise in a given track. So, for example, if you have viewed the code for Hamming in Ruby submitted by 100 different people, then you will have 100 rows in the views table. If you then say "mark all as read" for Hamming in Ruby, then you will have _one_ watermark which sets everything as read. At this point we can delete the 100 rows in the views table.
This rake task is intended to run on a regular basis using a cron job, for example once a day.
/cc @bernardoamc
> Add rake task to delete views below the watermarks

- lib/exercism/team_stream_filters.rb
- lib/exercism/track_stream_filters.rb
- test/exercism/team_stream_filters_test.rb
- test/exercism/track_stream_filters_test.rb
When we have a view timestamp that is outdated (the exercise has
a more recent timestamp than the last viewed at timestamp), but
a watermark that was newer, the exercise was getting counted as
unread.
@bernardoamc I realized that I had to compare to the `last_activity_at` on exercises instead of `mark.at` as we first discussed, since excluding the view based on `mark.at` would fail in the following scenario:
- last viewed at: Monday
- last activity at: Tuesday
- watermark at: Wednesday
In that case it would _not_ be counted in the "views" query, and then it would _not_ be counted in the watermark query, either.
Fixes #3154
> Fix unread count bug in stream filters

- lib/exercism/team_stream_filters.rb
- lib/exercism/track_stream_filters.rb
We count all the exercises that are marked as 'read' so that we can compute the
'unread' count for the sidebar navigation in each category.
Since some things will be marked as read both based on a watermark and
based on direct views, we would double count them. To avoid that we need
to either exclude the relevant views when counting the watermarks, or
exclude the relevant watermarks when counting the relevant views.
The performance of using NOT IN against the views table (7MM rows) was
dismal to the point of taking down production when certain users
accessed the activity stream.
This reverses the logic so we're excluding watermarks when counting
direct views.
/cc @bernardoamc I'm going to merge and deploy since I had to rollback the previous deploy.
> Reverse counting logic in stream filters

- app/helpers/fuzzy_time.rb
- test/app/helpers/fuzzy_time_test.rb
Fixes #3076 
This PR solves the timestamp problem referenced in #3076  , the problem is currently happening because we only consider the cases covering from 0 to 23.5 hours ago. We also also consider the case covering from 23.5 to 24 hours ago.
> timestamp_improvement, cover the case from 23.5 to 24 hours

- public/sass/application.scss
Don't mean to step on feet at all with these. I was chatting with @kytrinyx 
recently and looking at the home page specifically. I noticed that despite 
having a strong key color in the header, this key color wasn't used to direct 
attention to the call to action buttons lower on the page.
Those sort of act like "choose your own adventure" buttons, but as they stand, 
they sort of fade into the background of the page; looking more like links than 
actions. 
I've re-used the exercism red on these buttons and given them more of a button 
shape and appearance. This is just a first step and what I've suggested to 
@kytrinyx is that much of the copy currently used on the home page to explain 
each individual "path" that visitors can take depending on their skill-level 
should be transfered to …
> User experience experiments on landing pages

- lib/exercism/view.rb
- lib/tasks/views.rake
When an exercise has activity that is newer than the most recent view,
then the view isn't serving any purpose.
@bernardoamc I'm trying to find ways to shave off records from the views table, which is by far the largest table. This will delete over 100k records in production, which is not a whole lot given that we have over 7 million views, but every little bit helps.
> Delete obsolete view records

- lib/exercism/track_stream.rb
- test/exercism/track_stream_test.rb
Fixes #3133
This PR solves the pagination problem referenced in #3133 , the problem is currently happening because we only consider as active a problem stream or track stream filters, not the viewer filter. When we are in `My Solutions` we should consider the Viewer filter as active and paginate using its result.
> Fix viewer filter pagination

- lib/exercism/user_finished_tracks.rb
- test/exercism/user_finished_tracks_test.rb
Fixes https://github.com/exercism/exercism.io/issues/3029
This PR solves the ambiguity of how to determined user finished tracks in #3029  , the problem is currently happening because we count the completed exercises by number but some of the completed exercised are deprecated. We need to filter the deprecated ones first and then continue our counting.
TODO:
> Track completeness determination improvement

- app/routes/languages.rb
- app/views/languages/_topic_not_found.erb
- app/views/languages/language.erb
- test/app/languages_test.rb
We have a particular set of documentation topics for each track.
If you ask for a topic outside of that set, we were showing you the
page that says "we don't have that track, but Katrina can make you one".
It's not a track, it's a topic within a track.
This changes it to show you the documentation page for that track, with
an error message that makes more sense ("no such topic in the context of
track X").
Here's some screenshots.
/cc @nickborromeo @mhelmetag Want to sanity-check this really quickly? I'm hoping that this bit of cleanup will help make it a tiny bit easier to swap in Trackler in the language route.
> Disambiguate "missing track" and "no such topic"

- lib/exercism/user_tracks_summary.rb
Starting the investigation of #3181 
The goal of these changes is to avoid grouping exercises by language
in memory and N+1 queries for comments and submissions.
Did a few benchmarks and the changes looks solid. I tried as much as possible to avoid warming up  database indexes/queries. Here is the benchmark running locally:
**kotp and NobbZ before**
-------------------------------------------------
0.850000   0.060000   0.910000 (  1.237934)
**after**
0.010000   0.000000   0.010000 (  0.282434)
**kytrinyx before**
-------------------------------------------------
2.670000   0.210000   2.880000 (  3.749523)
**after**
0.030000   0.000000   0.030000 (  0.932170)
**etrepum before**
-------------------------------------------------
3.100000   0.220000   3.320000 (  4.374569)
**after**
0.010000 …
> Improve profile load time.

- app/routes/languages.rb
- app/views/languages/_contribute.erb
- app/views/languages/_todo.erb
- app/views/languages/language.erb
- test/app/languages_test.rb
- test/x/todos/todo_test.rb
- x/todos/todo.rb
- x/track.rb
The track todos were linked to from the track documentation page,
however the actual page was full-width, without the breadcrumbs or
the sidebar navigation for the track documentation.
This doesn't fix the scannability of the todos, but it does bring
this into line with the rest of the documentation visually/contextually.
I deleted a couple of tests that I'd like to add back in when we've refactored—this is in a pretty dirty/hacky area of the code, and the test would now require two fixtures instead of one.
Here are some screenshots:
FYI @nickborromeo @mhelmetag - this affects one of the areas that we're refactoring to use Trackler.
> Consolidate track todos with track documentation

- lib/exercism/language.rb
- test/exercism/language_test.rb
This helps with the refactoring in #3164
Throughout the codebase we ask "what is the name of the programming language for the track with ID `$ID`". We were asking over HTTP, now we don't have to.
/cc @nickborromeo @mhelmetag @bernardoamc
> Swap trackler into the "language" helper in lib

- app/routes/stats.rb
This is a PR onto the open trackler PR: #3164
The stats routes aren't linked to from anywhere and they're completely experimental, but track maintainers sometimes have a look at them.
/cc @mhelmetag @nickborromeo
> Swap trackler into stats routes

- frontend/config/application.coffee
- package.json
Lineman defaults to [grunt-concat-sourcemap](https://github.com/kozy4324/grunt-concat-sourcemap) for generating sourcemaps. Added it to `package.json` and copied generated sourcemaps to `/public`.
Issue #3199
PS: [grunt-concat-sourcemap](https://github.com/kozy4324/grunt-concat-sourcemap) is deprecated but lineman uses it as default for generating sourcemaps, hence using with the same.
> Generate sourcemaps for js and css

- lib/tasks/db.rake
Previously we were failing if $CHILD_STATUS wasn’t success but
that can be the case simply when the config.database already exists in
psql.
With this we simply check to see if we have a matching database when
the status isn’t success, and output a helpful feedback message.
This allows bin/setup to be run multiple times without failure.
> Don’t fail if development DB already exists

- app/routes/languages.rb
- app/views/languages/_about.erb
- app/views/languages/index.erb
- test/app/languages_test.rb
Part of #3164
Instead of using Xapi calls to get information about languages, the language route now uses the Trackler gem.
The main benefit of this is to no longer have to stub out requests since the information is now coming from the Trackler gem's fixtures. 
Some of the views were also changed in order to make use of some new variables introduced.
> Refactor Xapi out of languages route

- api/v1/routes/tracks.rb
- test/api/tracks_test.rb
Helps with https://github.com/exercism/exercism.io/pull/3164
This removes the call to `Xapi` from the route that checks the status of
the language. It now uses the Trackler gem to determine if the the track
exists.
The variable name of the route was also changed from `id` to `language`
so that it makes a little more sense.
> Use Trackler for Tracks Route

- app/views/languages/_contribute_exercise.erb
- app/views/languages/_todo.erb
- public/sass/base/components/languages.scss
This pull request solves issue #3192.  I moved the exercise list from a grid view to a table view.  
I also included some handing for smaller screen sizes.
> Make track todos scannable #3192

- app/views/account/show.erb
This adds a description of teams to the account page about the team details which follows in line with the other descriptions on this page. This should address #1673 and uses the description provided by @mandel01. 
If we want to also add information about teams to the help that can be done also.
> Add a description of teams on the account page

- lib/tasks/db.rake
- lib/tasks/test.rake
There is code that is executed regardless the task you are mean to execute, for examples, if you try to do rubocop, it will always try to connect... 
This also will get some improvement on how much time it takes to run a task:
``` sh
$ time rake rubocop
Running RuboCop...
Inspecting 212 files
....................................................................................................................................................................................................................
212 files inspected, no offenses detected
real    0m10.431s
user    0m3.100s
sys     0m6.356s
$time rake rubocop
Running RuboCop...
Inspecting 212 files
............................................................................................................................................ …
```
> db.rake & test.rake should not do code outside task context

- docs/fixing-exercise-readmes.md
- docs/getting-involved-in-a-track.md
- docs/improving-consistency-across-tracks.md
- docs/maintaining-a-track.md
- docs/porting-an-exercise.md
- docs/triaging-issues-in-a-track.md
@exercism/track-maintainers I've been working on documenting more of the work that's involved in contributing to a language track. I think that if we can get this properly documented, we can do a bit more around explicitly trying to find more people to contribute (and eventually to maintain) the tracks.
I'd love feedback about anything that catches your eye. Clarity, missing topics, correctness, whatever it is.
View the rendered files:
- [getting involved in a track](https://github.com/exercism/exercism.io/blob/language-track-docs/docs/getting-involved-in-a-track.md)
- [triaging issues](https://github.com/exercism/exercism.io/blob/language-track-docs/docs/triaging-issues-in-a-track.md)
- [improving consistency across tracks](https://github.com/exercism/exercism.io/blob/language-track-docs/ …
> Add documentation about contributing to tracks

- docs/reviewing-a-pull-request.md
* Jekyll attribution link was broken due to internal refactoring.
> Fix a broken link in reviewing a PR doc

- app/helpers.rb
- app/helpers/css_url.rb
- app/routes/core.rb
- test/app/helpers/css_url_test.rb
When setting up an Exercism development environment, if the application.css file has not been generated the error message is not very helpful, the new message provides more details about what went wrong and what can be done to rectify the problem.
Old message:
>Errno::ENOENT at /
No such file or directory @ rb_file_s_mtime - ./public/css/application.css
New message:
>IOError at /
'\<developers exercism.io path>/public/css/application.css' not found.
Try running 'bundle exec compass compile' to generate it.
For more information: https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#scss
> Development: Give a helpful error message if css not generated.

- CONTRIBUTING.md
The Exercism web application is primarily a Sinatra app and NOT
a 'Ruby on Rails' app.
This patch replaces references to 'Ruby on Rails' to simply 'Ruby'
> CONTRIBUTING.md: Remove misleading references to Rails.

- Gemfile.lock
- app/views/languages/_contribute_exercise.erb
- app/views/languages/_todo.erb
- app/views/languages/contribute.erb
Closes #3266
We've been working on swapping out the x-api calls to use the Trackler gem directly. I missed the fact that the contribute/todo page hadn't gotten updated in the mix.
This changes the erb files to use the Trackler gem.
/cc @ferhatelmas who reported the issue, and @Insti @tejasbubane who have done work to fix it.
> Fix broken language contribution pages

- test/app/languages_test.rb
For now this just includes test cases which should fail as per issue #3266 
@Insti has sent a [fix to trackler](https://github.com/exercism/trackler/pull/8). If any changes are required here, I will update this PR accordingly.
Includes:
* Test routes against all topics.
* Use `language` instead of `track` and maintain consistency through the test file.
* Reorder some tests for better reading.
> Add tests for all topics on language pages

- app/views/languages/_about.erb
Add missing 'fetch' to fetch instructions on the language "about" page.
> Add missing 'fetch' to fetch instructions. Fixes #3270

- lib/exercism/team.rb
Fixes #3275
We don't really need to count the manager when getting the number of members for a team.
@Insti Can you review this one? :)
> Ignore manager when counting number of members in a team.

- lib/tasks/accounts.rake
By default if you change your username on GitHub, then we will update
the username on Exercism the next time you log in.
However, sometimes people create a new GitHub account and either just
leave the old one in place or delete it, and then want to merge their
two exercism accounts.
When someone makes the request we should be very careful that the two
accounts do, indeed, belong to the same person. If the older account no
longer exists, then it's less important to be able to connect this to
the same email address in both cases, but whatever we do, we should
pay attention.
Fixes #3242 
/cc @kotp @Insti @bernardoamc would one of you have time to review this? It's not a critical code path and so it doesn't need to be beautiful, but it does need to be correct :)
------
Note to self: the …
> Add task to merge accounts

- app/presenters/profile.rb
- test/acceptance/profile_test.rb
Fixes #3273 
We want to display only the current teams of an user for the rest of the world, unless we are seeing our own profile.
@kotp Can you review that? Thanks for the issue. :)
> Show team invites only when the current user is in its own profile.

- public/sass/application.scss
Follow up to #3291. 
Minor fix to set apart the exercism wordmark from links in the sidebar without adding visual noise.
For convenience:
Before
After
> Improves wordmark in navbar.

- app/views/submissions/current_submission.erb
- public/sass/layouts/submission.scss
In #3287 I shouldn't have used absolute positioning for the buttons because it doesn't play nice when the browser window is zoomed.
I removed the absolute positioning and the bottom border of the buttons, so it will align correctly at any zoom level.
This is the before:  
This is after:  
Here is a close up. I also removed the little radius on the top right corner of the code block window.
Let me know if this looks okay or if you have any suggestions.
Thanks!
> Fix mis-aligned copy/expand buttons

- .travis.yml
- Dockerfile
- Gemfile
- Gemfile.lock
Previous attempt at upgrading to 2.3.0 was reverted due to lot of
errors in the logs (4b96e0b)
I saw following errors this time:
```
Thread.exclusive is deprecated, use Mutex
```
And found that these were coming out of `sinatra-contrib` which was
fixed in `1.4.7`:
https://github.com/sinatra/sinatra-contrib/issues/183
I suspect the errors were same with `2.3.0` at that time which were
intercepted by newrelic (we no more use newrelic).
Upgrading `sinatra-contrib` to `1.4.7` fixed the errors.
> Upgrade Ruby to 2.3.3

- x/docs/md/cli/mac.md
When looking at the docs for setting up the CLI in Mac OSX and Windows, I noticed that the titles in both pages were formatted differently and the phrasing for part of the content was slightly different as well. Additionally, some of the titles in the Mac OSX were a bit misleading (like `#### 2: Install Homebrew`) and some of the content was duplicated.
This PR is an attempt to remove these minor errors and bring both pages closer together.
> Make titles for Mac OSX and Windows docs more consistent

- frontend/app/js/app.coffee
A bug was identified (https://github.com/exercism/exercism.io/issues/3289) where a comment persists in localstorage after submitting. This occurs due to the keydown event to submit and clear localstorage, firing before the keyup event that stores the comment in localstorage. This is somewhat difficult to test locally as you need to insert a `sleep` method into `app/routes/comments.rb` to ensure the server takes sufficiently long to respond that `keyup` has time to execute.
To resolve this we only store a comment if it has changed, which is not the case with a submission.
> Only store comment in localstorage if it has changed

- lib/exercism/track_stream_filters.rb
The `unread` badges in the activity stream sidebar menu disappear after clicking `mark all as read`. Even after new submissions and iterations are added, the badges don't reappear if there are any (unlocked) archived submissions anywhere in that track. After clicking `mark all as read` the `watermarked` query returns every submission in the track-unlocked-problem group, even archived ones. So if there are 10 archived submissions the number unread is calculated as -10. The `unread` badge is hidden when its less than one. It will stay hidden until 11 new submissions are added, and then it will display 1 instead of 11.
Excluding the archived submissions from the `watermarked query` seems to fix the issue, at least in my testing in the development environment. 
Resolves: #3295
> Exclude archived exercises from activity stream

- frontend/config/application.coffee
- frontend/config/files.coffee
Should resolve: https://github.com/exercism/exercism.io/issues/3261
I noticed that that although the minified JS files are being generated they are not being copied into the /public directory. So I've set that up and turned off copying the dev assets as part of a dist build to stop that happening in future.
I've also done a bit of cleaning up in Lineman, by removing CSS (since compass is taking care of that) and cleaning up quotes and coffeescript.
There's scope for a fair bit more cleaning up and getting more out of lineman / asset set up.
> Serve minified JS + a little ❤️ for lineman

- frontend/app/js/script.js
Toggling the current submission layout between side-by-side
code/comments and full-width code/comments scrolls the browser
window as necessary to keep the code in view.
Resolves #3288
> Keep submission window in view when expanded

- CONTRIBUTING.md
- docs/setting-up-local-development.md
Move this from `CONTRIBUTING.md` to `docs/setting-up-development.md`, so that it's 
easier to understand and link to.
I've also reordered some of the sections in it to make it easier to get to the point where you have the app running.
See issue https://github.com/exercism/exercism.io/issues/3251
> Split "setting up development" into a separate guide

- api/v1/routes/tracks.rb
At the moment we've got broken images in the track documentation pages. We've been working around it by referencing the full path to the x-api endpoint that can serve them, which is kind of awful.
This lets us serve the track images directly from the exercism.io API. The next step is to use the new support for configuring the actual track documentation image paths when calling the trackler documentation function.
See:
- https://github.com/exercism/exercism.io/issues/3312
- https://github.com/exercism/trackler/pull/15
> Add endpoint supporting arbitrary track images

- Gemfile.lock
- app/routes/languages.rb
- app/views/languages/_installing.erb
The track documentation often needs to contain images, and those images live in the track repository. This means that when the documentation refers to "/docs/img/test.png", that is in the track repository, not in the Exercism repository.
When we parse the markdown, the HTML creates an image with a source that has a URL which is relative to the Exercism site.
We need to rewrite the image path to use the API endpoint which serves track images.
See https://github.com/exercism/xswift/pull/212
> Configure track documentation image path

- docs/writing-track-documentation.md
This addresses confusion that is documented in #3312
> Explain how to document a language track

- app/views/site/index.erb
There is an extra an in the index page that I took out.
Fixes: #3321
> Remove extra 'an' from front page

- docs/writing-track-documentation.md
A line referencing some help about how to link to images in Markdown should be out of a block of formatted code.
In my opinion, that line looks better out of that block. Feel free to reject this PR if it's not.
> Documentation: Extract text line out of formatted code

- package.json
Previous lineman was using old version of `grunt-contrib-jshint` package which had [an issue](https://github.com/linemanjs/lineman/issues/391). Also lock lineman to specific version instead of using `>=`.
Fixes #3120.
> Upgrade lineman to latest version 0.37.0

- docs/inviting-new-maintainers.md
This stems from https://github.com/exercism/discussions/issues/105
The summary of my motivation for adding this document is that it's up to
us (existing maintainers) to invite new maintainers. However, I had
always been reluctant to in the past, because I did not know how to do 
it or what to say!
This file records what we agreed upon in the discussion to fix the 
problem of "I don't know what to say when inviting a new maintainer!"
> docs: add explanation of inviting new maintainers

- app/views/languages/_launch.erb
This fixes #3351 .
I choosed to hard-code `LAUNCH.md` into the erb template.
> Fix help launch view for new tracks

- app/views/application/footer/links.erb
This should take care of #3332.
I just changed the link text to 'Install the Command-Line Client', instead of 'Download and Install the Command-Line Client', since the act of installing means that you will have to download the CLI.
> user should know that link leads to install page

- app/views/application/_footer.erb
We've put in place a nifty guide as part of #3187.  This change points website users to that guide.
> Point contributors to the guide in the repo

- README.md
Part of #3187.  This commit attempts to remove redundancy created by the "new" guide.
> Point contributors to our Contributing Guide

- x/docs/md/help/executable.md
Running "exercism configure --dir" doesn't appear to work as described.
```bash
$ exercism configure --dir
Incorrect Usage.
NAME:
exercism configure - Writes config values to a JSON file.
USAGE:
exercism configure [command options] [arguments...]
OPTIONS:
--dir value, -d value   path to exercises directory
--host value, -u value  exercism api host
--key value, -k value   exercism.io API key (see http://exercism.io/account/key)
--api value, -a value   exercism xapi host
2017/01/14 08:43:05 flag needs an argument: -dir
```
In any case, it was right there in the debug output; why not do the same as the API Key above and just say look at it?
> Documentation: Elide "exercism configure --dir" with no value

- app/routes/teams.rb
- test/app/teams_test.rb
If you try to open a team stream on a specifi user for instance : 
[/teams/baconesia/streams/users/beth](http://localhost:4567/teams/baconesia/streams/users/beth) you'll see that the last part of the sidebar contains a list of links. One link for each track the user's worked on.
For example:
[/teams/baconesia/streams/users/beth/tracks/coffeescript](http://localhost:4567/teams/baconesia/streams/users/beth/tracks/coffeescript)
This link is built by a `TeamStream::UserFilter` object but the relative url this object returns does not match with an existing route.
Add the relative route on `app/routes/team.rb`file
> Add missing team stream route for user by track

- app/views/submissions/show.erb
- frontend/app/js/preview.js
- public/sass/layouts/submission.scss
When viewing a submission with multiple iterations, hovering the mouse over an iteration's tab will cause that iterations code to be displayed in the code view window(s). This is a way to quickly see the differences between iterations by hovering back and forth between tabs.
Starting with an exercise with two iterations:
Hover over the tabs to quickly see the changes:
Related to #3307
> Add quick preview of other iterations

- app/routes/teams.rb
- lib/exercism/team.rb
- test/acceptance/profile_test.rb
- test/acceptance/team_test.rb
- test/app/invitations_test.rb
- test/app/teams_test.rb
- test/exercism/team_test.rb
- test/exercism/user_test.rb
Fixes #3110 
Right now the manager is already being added as a member, so we don't need to send the invite.
To solve the problem we have to make sure that the team is created properly and the manager is added as manager before inviting members from the usernames list.
> Do not invite manager as member when creating a team.

- test/app/teams_test.rb
We are required to explicitly invite members in our tests until we come up with a good abstraction for this workflow.
> Explicitly invite members in tests.

- docs/setting-up-local-development.md
The title for setting up exercism.io with Docker mentions using vagrant,
yet vagrant is not actually mentioned or used for the docker setup.
> setting-up-local-development-environment: remove references to vagrant

- docs/setting-up-local-development.md
Line 45 previously stated this:
`1. Run exercism.io on your computer directly by [installing the required software](#running-exercism-io-directly-on-your-computer).`
And linked to the section immediately below it.  I thought the link was broken until I saw it was just referencing the section directly below the current one. I think it would clarify this if the line was changed as proposed, to just reference the following section.
> Clarify setup on local machine

- docs/setting-up-local-development.md
This fixes issue #3393.
Correct a typo in the Foreman command for [local setup](https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md#run-exercismio-locally) by removing '-'.
> correct typo

- app/views/layout.erb
Fixes #3397. 
Essentially just adds a check in the layout.erb page - if the url includes `/submissions/` it will add the nofollow/noindex meta tag. I'm not sure if this is the best way to do it, but it certainly *appears* to be the simplest. Let me know if there are any changes you'd like me to make.
> add robots nofollow/noindex meta tag to submission pages

- docs/setting-up-local-development.md
When I was setting up my dev environment I noticed the word "install" was missing from here:
```
$ sudo apt-get update
$ sudo apt-get rbenv ruby-build
$ rbenv install X.Y.Z
```
So I changed it to this, which is runnable and works:
```
$ sudo apt-get update
$ sudo apt-get install rbenv ruby-build
$ rbenv install X.Y.Z
```
Also added a "sudo" to the Postgre-SQL instructions cause it needs that (just in case someone's not as Linux-savvy as they think they are 😄 )
> Fix Linux set-up instructions

- docker/README.md
Docker as released an easier way to install their software on both Mac
and Windows machines. This adds the links to those executables so that
people setting up for the first time will have less of a barrier when
using Docker with this project.
> [Docs] Update Docker ReadMe with new install paths

- app/views/user/_archived_exercises_table.erb
The profile page has a separate section for archived exercises, which was using the
capitalized track ID instead of the language name. This resulted in things like 'Cpp'
and 'Fsharp' instead of 'C++' and 'F#'.
Tested locally by looking at a profile with C++ and F# exercises on it.
Fixes #3399
> Fix inconsistent labels on profile

- x/docs/md/cli/windows.md
Issue #1844 highlights the missing information of how to uninstall the Exercism CLI tool.
This change adds a small section on how to uninstall the package using Chocolately, the package manager already used in the docs. It shows the use how to use the `uninstall` command.
Another change made here was to fix the broken images on the page. When I first loaded the page I saw these broken links:
> [Docs] Update docs for Exercism CLI on Windows

- api/v1/routes/iterations.rb
- lib/exercism/iteration.rb
- test/api/iterations_test.rb
Fixes #3390.
Previously if a user renamed a directory with non-lowercase characters,
submission would fail because Trackler would fail to find a matching
track.
This fixes just the endpoints mentioned in the issue. Do we need any URLs to be capitalized? I'm wondering if a better solution would be to normalize casing across all endpoints?
> Make track-id(language) & slug(problem) lowercase

- Gemfile
- Gemfile.lock
- app.rb
- config.ru
- db/migrate/20170313231200_create_flipper_tables.rb
- docs/flipper-feature-flags.md
- lib/exercism/guest.rb
- lib/exercism/user.rb
- lib/flipper_app.rb
- lib/flipper_app/authorize.rb
- test/exercism/guest_test.rb
- test/exercism/user_test.rb
- test/flipper_app/authorize_test.rb
This patch introduces the [flipper][] gem, which satisfies all the requirements listed in #3407. I chose this over alternatives, because it's self-contained (no third party involved), works with ActiveRecord (keeping dev setup consistent), and does exactly what we want.
This will be used to turn on and off experiment features and roll out to a random 50% experiment group described in https://github.com/exercism/discussions/issues/123.
[flipper]: https://github.com/jnunemaker/flipper
Todo:
For authentication, I imagine I could hard-code @kytrinyx and myself in production, but is there a more appropriate existing group?
> Add feature flag support with flipper

- config.ru
- config/flipper.rb
- lib/exercism.rb
This is a followup to #3408.
Previously, it was defined only for the app server, not the console or tests.
> Make Flipper available in all environments

- .rubocop.yml
- api/v1/routes/core.rb
- api/v1/routes/iterations.rb
- api/v1/views/attempt.pg
- test/api/assignments_test.rb
- test/fixtures/approvals/api_multifile_submission_accepted.approved.json
- test/fixtures/approvals/api_submission_accepted.approved.json
- test/fixtures/approvals/api_submission_accepted_on_completed.approved.json
This is paired with https://github.com/exercism/cli/pull/377 but does not need not need a synchronized release. This change forward/backward compatible, tested in all combinations of new & old exercism.io and new & old cli.
In clients that support it, the "what next instructions" will be displayed after a new iteration is submitted.
This allows us to modify the message anytime, without having to wait for users to update their cli version.
Part of the experiment outlined in https://github.com/exercism/discussions/issues/123.
> Introduce "what next instructions" to submission API response

- x/docs/cli.rb
- x/docs/md/cli/completion.md
- x/docs/md/cli/linux.md
- x/docs/md/cli/mac.md
- x/docs/md/cli/windows.md
This addresses https://github.com/exercism/exercism.io/issues/3402, which pointed out that the CLI completion scripts that are documented on http://cli.exercism.io/ aren't mentioned on [the main CLI pages](http://exercism.io/cli).
I made some slight copy tweaks from the original on http://cli.exercism.io that I think match the style of the surrounding content. The content is the same for Mac, Windows, and Linux, but I opted to include it on each individual page instead of creating a new tab to make sure that new users would see it as they installed the CLI on their OS. (I'm on a Mac, and the instructions worked well for setting up Bash completion on my machine, although I didn't test out Zsh or anything on Windows or Linux.)
> Add documentation about CLI completion scripts

- db/migrate/201703132312_create_flipper_tables.rb
This migration was created following the rails convention of including
seconds digits in the id, rather than the project convention.
Since this migration may already have run in some environments, this
patch cleans up after the rename.
* The migration is renamed
* The old migration id is discarded in `schema_migrations`
* If the migration work was already done, return and do nothing.
> Follow project migration id naming convention

- docs/overview-architecture.md
The link to the [sequence_diagram](https://github.com/exercism/exercism.io/blob/master/docs/img/core_flow_sequence_diagram.png) introduced with https://github.com/exercism/exercism.io/pull/3411 is broken.
With this PR we fix the link.
> Fix link to sequence diagram image

- app/routes/user_exercises.rb
- test/app/exercises_test.rb
This addresses https://github.com/exercism/exercism.io/issues/3381. Instead of redirecting a user to the dashboard after archiving or unarchiving an exercise, this redirects the user back to the exercise page for further review.
> Redirect user back to exercise page after (un)archiving

- api/v1/routes/iterations.rb
- test/api/assignments_test.rb
> Recommended naming conventions: lower case, snake case, underscores over dashes. 
> Good: foo_bar, foo.
> Bad: FooBar, Foo Bar, foo bar, foo-bar.
—/flipper/features/new
> Follow flipper-suggested feature name convention

- lib/exercism/client_version.rb
- test/exercism/client_version_test.rb
This was a quick-edit and no manual test, verifying doubles, or integration test failure.
It was a win for feature flags though. Even though the bug was merged to master, it would never be noticed without the feature flag being enabled.
> Fix transposed method names

- x/docs/md/cli/completion.md
I made a typo in my original PR that included documentation about how to set up Zsh completion, and @felixbig kindly pointed it out here: https://github.com/exercism/exercism.io/pull/3415#discussion_r107943395
> Fix typo in Zsh completion instructions

- app/views/submissions/current_submission.erb
- frontend/app/js/app.coffee
- frontend/vendor/js/underscore.js
- public/sass/base/components/callout.scss
- public/sass/base/components/import.scss
- public/sass/layouts/submission.scss
Implement suggestion 1 in https://github.com/exercism/discussions/issues/123#user-content-proposed-changes.
* A thought-provoking prompt appears under the code submission.
* A new comment button focuses the comment box—helpful when it's buried under a long list of comments, and because it connects what to do with your response.
* A reload button supplies a new thought
Feature flag: `prompts`
Todo:
Initial Prompt Questions
-------
- Are there any complicated bits that deserve to be named/abstracted using a function or variable?
- Are there any edge cases or unexpected inputs that aren't handled?
- Are there any intermediate variables or functions that could be extracted to give a name to some concept, making the code easier to scan and understand its intent?
- Could and should this code be …
> Suggest "food for thought" prompts on submissions

- docs/setting-up-local-development.md
Using port 4567, I couldn't figure out why my JS wouldn't reload with lineman building things for me. Hopefully this will help others later who hit the same problem.
> Document that port 8000 must be used for lineman reloading

- Gemfile
- Gemfile.lock
- config/flipper.rb
- lib/monkey_patches/flipper/gates/percentage_of_actors.rb
- test/monkey_patches/flipper/gates/percentage_of_actors_test.rb
This is for the exercism/discussions#123 experiment.
Override to consider only the actor value (GitHub username), not the feature name, to provide a consistent control group across features, rather than a different 50% for each feature.
This new test fails without the monkey patch. Considering the boolean output and the random-like nature of Zlib.crc32 output ([the hashing algorithm used][crc32]), 250 iterations should more than cover it. The test completes in 40ms on my machine.
[crc32]: https://github.com/jnunemaker/flipper/blob/v0.10.2/lib/flipper/gates/percentage_of_actors.rb#L33
> Monkeypatch Flipper to provide a consistent control group

- lib/exercism/syntax_highlighter.rb
ref: #3450
Rouge doesn't know what delphi is so we need to map delphi to pascal.
> Map Rouge highlighting for delphi to pascal

- docs/setting-up-local-development.md
This fixes issues #3459 , 'Anchor links broken in setting-up-local-development.md.'
Removing the extra '-' in link fixes anchor links.
> Fix broken anchor links

- app/routes/static.rb
- app/views/application/footer/links.erb
- app/views/languages/_about.erb
- app/views/site/cli.erb
- app/views/site/how_it_works_newbie.erb
- test/app/static_pages_test.rb
This fixes issue #3442 to put '/cli' and future '/gui' routes under a namespace, ('/clients').
Changes:
- all '/cli' routes are now namespaced under '/clients'
- test for '/cli' in app/test/static_pages_test.rb has been updated with namespaced URL
- all links to cli docs have been updated with '/clients' prepended to URLS
Some questions: 
- We can make more changes, like conflate the routes using an array like this: 
`%w(mac windows linux install).each { |topic| get "/cli/#{topic}" do ... }`
Don't know if that makes it unclear to read, but may be worth it? 
- Should the filename of the erb  file in /app/views/site/ be changed from cli.erb to clients_cli.erb?
- There's only 1 test for the /clients/cli route; is it because testing the content of the pages, (/clients/cli/linux for example) …
> Namespace all /cli routes under /clients

- app/presenters.rb
- app/presenters/track.rb
- app/routes/languages.rb
- test/app/presenters/track_test.rb
https://github.com/exercism/exercism.io/issues/3356 highlighted that when a language topic page is missing content, it shows a blank page instead of the fallback content in [x/docs/md/track](https://github.com/exercism/exercism.io/tree/master/x/docs/md/track). This functionality likely broke when we switched over to using Trackler to grab content for these pages.
Since the normal content for these pages lives in Trackler but the fallback content lives in this repo, this PR creates a wrapper around tracks returned by Trackler and inserts the fallback topic content when Trackler doesn't have any. The wrapper delegates everything else back to the Trackler track.
This could use some polishing and tests (could be a little tricky since we'll want to stub out Trackler), but I wanted to get a …
> Use fallback when language is missing topic content

- x/docs/md/cli/mac.md
- x/docs/md/cli/overview.md
- x/docs/md/cli/windows.md
This fixes two issues with the content of cli docs: 
- Fix broken image links by removing /public
- Fix links in content of some of the cli docs by updating to new /clients routes
> Update links in cli docs

- x/docs/md/intro/getting-started.md
The link to cli in the "how it works" section in the docs (http://exercism.io/how-it-works) is broken. You end up in a 404.
> Update link to command line client in docs

- app/presenters/track.rb
Adding `image_path` keyword to track.docs call eliminates the deprecation warning.
> Eliminate deprecation warning caused by track.docs call

- CONTRIBUTING.md
Referencing #3483. Dead link from dead repository. Will keep in mind about PR Hijacking.
> Get rid of dead link

- lib/exercism/team_membership_invite.rb
Sending a team invitation means creating a record in the database. As
long as that record exists, we will show a notification saying that
you're invited to a team.
Accepting a team invitation will create a new record, one that
references both the user_id and the team_id. We have a unique index on
this record.
In the case where (for some reason) the invite record fails to get
destroyed, we will be in the unfortunate situation of having (1) a
notification about being invited, and (2) a 500 error if you try to
accept it (because you've already accepted it).
This change forces a rollback of the database transaction if we fail to
delete the invite record.  This will remove the team membership record,
and allow them to try again.
Closes #3455
> Force rollback on failed data cleanup

- app/views/teams/manage.erb
This PR addresses #3477 
The remove buttons under the Managers section do not line up with the
ones under the Members section. For consistency, this commit applies
similar styles to all remove buttons under the sections mentions above.
The form that renders the remove button and the manager's gravatar
was wrapped in a `col-*` class that aligns with the one used under the
members. The css classes on the button were also changed to be similar
to the ones under the members.
No however I feel that since we are using the same class on both buttons,
we can perhaps remove the duplicate class (i.e. we can remove either one
of `.manager_delete` or `.member_delete` and remove the other to
something more generic such as `.person_delete`, I am open to
suggestions on the class name)
1. While I was in …
> Reposition the remove buttons on team management page.

- app/routes/static.rb
Closes #3470, which suggests removing the temp route for Let's Encrypt -- this minor PR makes that change. :)
> removes letsencrypt temp route

- CODE_OF_CONDUCT.md
Following a talk from the last person to update this file (small world!), I've put in the changes from the latest Contributor Covenant version.
One part I altered from the original was the text `contacting the project team at`, are you still using your own email for this @kytrinyx ?
> Update COC to latest Contributor Covenant version

- app/views/layout.erb
CrazyEgg is no longer being used.
This reverts commit 6b6b34bbf2536ebb081d4272bf070d349816839f.
From the discussion on github about the change:
@Insti
> Have we learned anything from crazyegg?
@kytrinyx
> I'm pretty sure I deleted it when the free month was up. Or at least the
> account. But yeah, we did: most people go straight to the /languages
> page, so we should show what languages we have available on the
> homepage.
Ref: https://github.com/exercism/exercism.io/commit/6b6b34bbf2536ebb081d4272bf070d349816839f
> Revert "Add crazyegg experimentally"

- frontend/app/js/script.js
`h:mm` displays the time in 12 hour format. There is no distinction between AM/PM here, so changing to `H:mm` for 24 hour format.
> Show time in 24h format

- app/routes/core.rb
- app/routes/legacy.rb
- test/app/static_pages_test.rb
- test/app/teams_test.rb
Use sinatra 2.0 feature to allow trailing slashes. (ref: https://github.com/sinatra/sinatra/pull/1273/commits/2445a4994468aabe627f106341af79bfff24451e)
As per discussion in #3428.
> Handle trailing slashes in routes

- app/views/languages/index.erb
- public/sass/base/components/languages.scss
Fixes #3325.
**BEFORE:**
**AFTER:**
> Use Flexbox instead of Bootstrap’s grid for languages list

- app/routes/contribute.rb
- app/views/contribute/canonical_data.erb
- test/app/routes/contribute_test.rb
Supersedes: #3514
Trackler already provides all the repository URLs we need to use in the `erb` template.
Use them instead of constructing our own.
Fixes hardcoded link to `accumulate` description.
Use a default value for slug so that the page still renders correctly when no slug is provided.
Use other Trackler supplied instance methods rather than fetching them again.
Add blurb so we know what the problem is about.
:tada: Added tests 🎉
> Use trackler-provided URLs in /contribute/canonical-data

- app/views/user/_track_progress.erb
This looks logically to me to have a reference to the language within profile page, so the user can easily jump to it and continue to work on exercises. At least I tried to click it intuitively few times.
> Reference a language on a profile page

- lib/exercism/team_membership_invite.rb
- test/exercism/team_membership_invite_test.rb
I'm still not sure how this happens, but we sometimes get a membership invite (confirmed or not),
that still has a membership invitation lying around.
This was raising an exception and failing to confirm the invite.
This adds tests for both of the cases, and does the right thing, adding the user
to the team and deleting the invite.
Fixes #3518
> Handle dirty membership data

- app/views/dashboard.erb
- app/views/site/teams.erb
Resolves #3428
Added descriptions for joining teams in both the `teams/about` page and the `dashboard`.
> Add join team description

- config.ru
In order to reference the long-winded environment variables like LOAD_PATH and
ERROR_INFO we need to explicitly require the English library.
This will fix bugsnag's reporting, since reporting  without English
means that we're reporting ; by definition: not an error.
Resolves #3469
> Require the english library

- app/helpers/track_image.rb
- app/views/submissions/show.erb
Resolves exercism/discussions#146
I think that the title text (hover text) for the icons is fine how I've implemented it. I also added the language name in the code/discussion title, but I'm thinking that people might not like it. Most of the time you'll know what language it is already, so it's probably not necessary.
This a screenshot of what it looks like:
> Added title text to language icons.

- lib/tasks/db.rake
When resetting the database you always want to run the db:migrate task to update to the latest schema. This patch adds the migrate step to reset so this will happen automatically for you.
It will then helpfully suggest the next step, which is seeding the database. Unless you are resetting the testing database, where seeding is undesirable.
If you wanted to avoid the migration step you can still run:
```
rake db:drop db:create
```
> Add db:migrate step to db:reset

- lib/tasks/seed.rake
The tests expect an empty database.
If you seed the test database a lot of tests fail.
This patch aborts the rake task without seeding if it is run against the test database.
> Rake: Don't seed the test database.

- README.md
GitHub now displays the license on the project home page based on the LICENSE file.
> Delete unnecessary license data from the README

- config/database.yml
Based on the puma README (https://github.com/puma/puma#configuration) it looks like the default
max thread count is 16.
According to Heroku's documentation (https://devcenter.heroku.com/articles/concurrency-and-database-connections#threaded-servers)
a reasonable default for Puma is the RAILS_MAX_THREADS value. I didn't find a MAX_THREADS value
for Sinatra, so I'm using Puma's default.
Fixes #3533 (maybe).
/cc @nilbus
> Increase the database connection pool in production

- app/views/submissions/show.erb
After seeing the language name in the submission title, it seems like the wrong place to put it. Removing it as per discussion in #3531.
Current view looks like this:
> Removed language name from submission title.

- app/views/submissions/show.erb
Added per discussion in #3531.
Submission description now reads `submitted in {{language}} by {{author}} {{date}}`.
This is what it looks like. This still has the language name in the title, but I assume we'll merge #3546 along with this one so it won't be there.
> Added language name in 'submitted by...' tag

- app/routes/profile.rb
Each page load generates a number of other asset requests, such as
/tracks/elixir/icon. Loading many of these at once, especially across
multiple concurrent users, has sometimes used up all the available
database connections in the DB pool.
The `page_request?` method is proven now and does not need to live behind
a feature flag.
> Only check $flipper feature flags for page requests

- docs/overview-architecture.md
This deletes project-wide topics and ensures that the copy reflects our current understanding.
The project-wide pieces of this have moved to:
https://github.com/exercism/docs/blob/master/misc/overview-architecture.md
> Clean up architecture document

- Gemfile.lock
- test/fixtures/approvals/markdown_double_braces.approved.txt
This caused an approval test to fail, but the received output actually
looks much more correct than the approved one, so I accepted the change.
Closes #3452
Fixes https://github.com/exercism/xcoq/issues/9
> Update rouge to latest version

- docs/setting-up-local-development.md
While reading the docs, I noticed that we can avoid confusion by linking
to the "Running exercism.io directly on your computer" section directly
instead of stating that the instructions are listed in the section after
it.
> Improve setting up local development instructions

- x/docs/md/cli/linux.md
Issue #1844 highlights the missing information of how to uninstall the Exercism CLI tool.
This change adds a small section to remove the exercism files from the
`~/bin` directory. This also adds a small suggestion to the user to also
clean up their `$PATH` variable if they wanted to.
> [Docs] Update docs for Exercism CLI on Linux

- docs/setting-up-local-development.md
This change was done because running tests without `bundle exec` complained about incomplete dependencies. Running tests without `bundle exec` was prescribed as a way to run tests individually in [Setting up Local Development#Testing](https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md#testing).
This issue was first raised in [#3558](https://github.com/exercism/exercism.io/issues/3558), and the solution agreed upon was to remove instructions to run tests without `bundle exec`.
> Remove instructions to run tests without `bundle exec`

- app/views/languages/not_found.erb
We used to say 'email katrina'. Now we have a request-new-language-track repo.
> Fix outdated documentation about requesting tracks

- test/app/languages_test.rb
- x/docs/md/track/BETTER.md
- x/docs/track.rb
We were previously guessing at the filename based on the topic and the most common file extension.
With the new DocFile implementation, we know the name of each individual file, regardless of what the
most common file extension is.
> Fix track doc filenames in 'improve this' text

- app/views/languages/_exercises.erb
- app/views/languages/language.erb
- test/app/languages_test.rb
While refactoring I found some rough edges, and added skipped tests for the things I wanted to fix.
This smooths them out, improving the readability and reducing potential confusion:
* don't tell people to ask for help on a track that has no exercises
* explicitly say so in the "exercise list" page if there are no exercises
* add a test for a doc file that we couldn't test with the previous fixtures
> Improve the track documentation section

- x/docs/md/track/TRY.md
with quotes it generate link like that "http://exercism.io/languages/rust/'/clients/cli'" but right path is "http://exercism.io/clients/cli"
> fix link to cli

- app/views/teams/manage.erb
Addresses #3575. If a Team had only one Manager, the following `<hr>` Members div would be outside of the container div. This PR closes the Manager rows div only when there is more than one manager. (Also, hi, this is my first OSS PR ever!)
> Team management closing `</div>` bug fix

- docs/setting-up-local-development.md
Changes are based on Ubuntu but should apply similarly to other distros:
- rbenv is likely to be outdated if installed via apt-get, better to clone from GitHub so that more recent Ruby versions are available via rbenv
- libpq-dev is required for PostgreSQL (specifically for the `pg` gem)
> Update rbenv and PostgreSQL steps for Linux

- db/migrate/201707080642_index_users_key.rb
I noticed in BugSnag that we were still seeing this error:
ActiveRecord::ConnectionTimeoutErrorapi/v1/routes/core.rb:46
could not obtain a connection from the pool within 5.000 seconds (waited 5.567 seconds); all pooled connections were in use
These tracebacks were not originating at many various database calls like I would expect, but rather all at the same one, which indicates to me that this [one call](https://github.com/exercism/exercism.io/blob/master/api/v1/routes/core.rb#L46) is responsible for a large portion of our database time.
```ruby
def find_user
User.where(key: params[:key]).first if params[:key]
end
```
Sure enough, there is no index for this common user lookup. Without it, the DB must scan all 150k users for each user lookup by key.
I think this should help with the …
> Index User lookup by key to address DB connection pool exhaustion

- .dockerignore
- Dockerfile
- Dockerfile.dev
- bin/setup
- docker-compose.yml
- docker/common.yml
This will drastically improve docker dev environment initial setup speed.  Rather than building locally, the local docker build (built from Dockerfile.dev) is now based on the public, automated exercism/exercism.io build (built from Dockerfile). With this as a starting point, a developer's `docker-compose build` need only install any new gems that are introduced in the feature branch. With no local changes, a local docker build, excluding download time, now takes approximately 6 seconds, vs. 50 minutes before.
@kytrinyx: Before merging this, you will need to create an Automated Build on Docker Hub. The new `Dockerfile.dev` build depends on this. This will result in Docker Hub hosting and building our Dockerfile each time you push to master on GitHub, such that people can `docker pull …
> Introduce a base docker image for layer caching purposes

- docker-compose.yml
- docker/common.yml
This enables the use of defaults with variable interpolation.
Followed procedure documented at https://docs.docker.com/compose/compose-file/compose-versioning/#version-1-to-2x
Several other Docker-themed PRs are coming shortly, all based on this commit to avoid conflicts.
[Diff with whitespace changes ignored](https://github.com/exercism/exercism.io/pull/3590/files?w=1)
> Upgrade docker-compose format to version 2.1

- docker-compose.yml
- docker/common.yml
Goal: Keep the database data around beyond the life of the DB container, and automatically attach it to new DB containers.
Without this, `docker-compose down` or otherwise removing the postgres container leaves orphan volumes that will not be reattached automatically.
Based on #3590 to avoid conflicts.
> Use a named Docker volume to better persist data

- Gemfile
- Gemfile.lock
- docker-compose.yml
- docker/README.md
- docker/common.yml
With no code reloading functionality in Sinatra, this I think is the next-best thing.
There is necessarily downtime after each `.rb` file change, while puma restarts. Modified `.js`/`.coffee` files take a few seconds to go into effect. Changes to `.erb` files go into effect immediately.
Restarting Lineman is a hack. Lineman really ought to instead be doing its own reloading.  It watches and compiles the files but doesn't put them in the right places to be effective. I have not spent the time to learn lineman well enough to fix it. Instead as a workaround, restart lineman, because starting lineman puts everything in its right place. See https://github.com/exercism/exercism.io/issues/2936#issuecomment-315500149
Based on #3592 to avoid conflicts.
> Docker: Rerun puma/lineman when relevant files change

- docker-compose.yml
- docker/README.md
- docker/common.yml
Convention over configuration.
With this first step no longer needed, move OAuth configuration lower in the README, relative to its importance.
Changing the port is already documented. Removed the redundant reference.
Based on #3590 to avoid conflicts.
> Provide a default port, making .env optional

- Dockerfile
A couple improvements on the base Docker image build:
- Install the version of bundler specified in Gemfile.lock
- Take advantage of bundler's parallelism
> Improve bundle install in Docker build

- app/views/contribute/index.erb
- app/views/languages/contribute.erb
- x/docs/md/track/TODO.md
The following link is pointing to an old docs page:
Changes done in this PR:
> Fix Porting an Exercise Link

- package.json
Closes #3557.
Should fix the [failing build](https://travis-ci.org/exercism/exercism.io/builds/273341130#L2296).
> Add testem to npm dependencies for lineman's spec-ci task to work

- app/views/submissions/comment.erb
This change makes comments containing curly brackets not bindable by Angular.
See: https://docs.angularjs.org/api/ng/directive/ngNonBindable
> Make the comment body non-bindable by Angular

- CONTRIBUTING.md
That helps frame this as details that you may or may not need depending on your experience with GitHub, and also emphasizes that we are happy to help, and that if a person is confused it's probably our fault, not theirs.
I suggested this tweak to the interactive CLI walkthrough, and @kntsoriano suggested it would be a good improvement here as well. I thought so too :-)
> Clarify introduction to workflow section of contributing guide

- app/views/languages/_todo.erb
I noticed on the C# page that this link is pointing to an old resource that no longer exists. I have updated it to the correct page.
> correct link to make-up-new-exercises.md

- app/routes/submissions.rb
- lib/exercism/comment.rb
- test/exercism/comment_test.rb
On the submission page we show a 'history' tab, which contains the most recent 50 comments. For people who comment in multiple tracks, this can contain a fair amount of less-relevant content.
The downside is that there might be some comments that people use a lot across all the tracks that they give feedback in. On the upside, it shouldn't be too hard to find that and copy/paste it the first time you need it in a new language track.
> Filter comment history by the submission's track

- CONTRIBUTING.md
Removed extra word; marked 'git push --force' and also some Git keywords as code.
> Fix formatting of inline commands in CONTRIBUTING.md

- app/views/submissions/comment.erb
Since exercism doesn't implement CSRF protection, a malicious site could submit comments on behalf of a user containing <script> tags that would execute when rendering that user's comment history. That script could send the user's cookie to a malicious party, who could then impersonate the user on exercism.
This patch escapes HTML in comment history, which in addition to being a security risk can interfere with the proper function of the page.
Fixes #3673
> Prevent reflected XSS via unescaped HTML tags in comment history

- app/routes/teams.rb
- test/app/teams_test.rb
Tags are already `downcased` when being persisted, so it makes sense to do the same for the provided term.
Related issue: #3738
> Allow case insensitive tag search in /teams endpoint

- public/sass/base/components/comment.scss
This should fix #3746. The css was already in place for any comments posted by the submitter, it was just scoped to tightly I guess.
**Before**
**After**
> Word-break links in all comments, fixes #3746

- app/routes/contribute.rb
Resolves https://github.com/exercism/exercism.io/issues/3730
The reason why the counter was always returning 1 as the count of canonical problems extracted was because the result of getting the array difference of `active_problems` and `need_canonical` (_which is also an array_) was enclosed in `[]` and `size` method was called on that element.
This meant that regardless of the result of the array difference, there will always only be one element in the array when calling `size`
This change fixes that issue by changing the delimiter from `[]` to `()` and calling `size`
___
> Fix canonical data counter

- x/docs/md/cli/windows.md
The Chocolatey Documentation includes directions on installing as a non-admin.  I have added a link in the help docs for that.
> Add link to to Non-Admin Chocolatey install docs.  Closes issue #3494

- app/views/teams/manage.erb
When a team has more than a single manager, the page layout gets all sorts of messed up :(
I was able to track this down to a few lines in the [manage.erb](https://github.com/exercism/exercism.io/blob/master/app/views/teams/manage.erb#L107-L109) template.
It was pretty hard to reason about the logic in the template so I broke it up into two scenarios
- there is a single manager
- there are more than one managers
There is likely some unnecessary duplication in the html in the view  now (this is my first time working with ruby and `.erb` files) but at least it renders accurately.
I also changed the delete button on the manager to a single `X` instead of `Remove` as it seems more consistent with the rest of the buttons.
> Correct layout problems when there is more than one manager for a team

- app/views/contribute/index.erb
Resolves https://github.com/exercism/exercism.io/issues/3758
A document was moved but the link to that document was not updated,
causing a broken link. This fixes the broken reference.
> Fix broken link in contribute page

- app/routes/sessions.rb
HTML escaping is all very nice, but it doesn't actually work for URLs.
Closes https://github.com/exercism/exercism.io/issues/3771
> Use URI escaping for GitHub login redirects

- app/views/application/_navbar.erb
- public/sass/base/components/banner.scss
- public/sass/base/components/import.scss
We have 1000 submissions a day. Some of those submitters must want to be mentors. But they probably have no idea v2 is a thing. Let's change that.
This PR adds a fixed bar above the navigation bar with a CTA. It's a little ugly, but with 4 weeks to go and a lot of exercism's future success riding on recruiting mentors, I think it's a pragmatic thing to do.
> Add a mentor recruitment banner

- x/docs/md/cli/linux.md
Small fix in uninstall path for Linux CLI. 
I would also update the instructions to mention 
that operations with /usr/local/bin require superuser permissions.
Should I do this in separate PR?
(Also sorry for any contributing mistakes - my first PR for a real project)
> Fix uninstall path in Linux CLI installation instructions

- public/sass/base/themes/exercism.scss
It was reported in https://github.com/exercism/exercism.io/issues/3785
that the nav bar was not rendering properly on the iPad.
Looking at the scss rules it looked like the rule to collapse the nav
bar was set to 768px which is the breakpoint for tablets in media
queries. Since it was within that range, that resolution was not
considered when determining if it should collapse the nav bar or not.
Bumping it up to the next breakpoint now collapses the items when
rendered from a tablet.
This resolves https://github.com/exercism/exercism.io/issues/3785
> Fix Navigation Bar on iPad (Tablet)

- x/docs/md/track/TRY.md
Right now the `Try it!` section does not contain very clear instruction about what file you need to submit to pass the exercise and does not mention that you can submit multiple files, or re-submit your solution.
This PR tries to address this problem.
> Expanded submission instructions in the 'Try it' section

- .appends/.github/labels.yml
@iHiD and I spoke yesterday and decided to use the `status/stale` label to indicate that we think
something is no longer a problem. We will comment in the issue thread
when marking something as stale, asking people to double-check.
If we don't hear anything back, we will close the issue.
This is not an automated process at the moment.
I forgot to add this description in the previous PR :/
Also I messed up when assigning colors, and accidentally assigned the `area/*` color to the `type/*` labels as well. This updates the `type/*` labels to be darker.
> Fix labels (a bit more)

- README.md
On the website's contact us and abuse page, it uses this email address and requests that [CoC] be put in the subject.
Probably worth having that in the README as well?
---
This was previous closed automatically. I believe I'm welcome to submit this now, though? ^-^'
> Yes, please update that
> 
> — https://github.com/exercism/exercism/issues/6352#issuecomment-1120443194
---
* https://github.com/exercism/org-wide-files/pull/220
* I actually ask some questions here. Depending on the answers I may rebase and edit the commit, so it's best if that is reviewed first.
> docs: coc section of readme
