exercism/exercism

.gitignore, lib/exercism/config.rb
Wouldn't it be nicer to base the configuration on the different config.json in the language tracks? Unfortunately I don't yet know the project well enough to do it myself ;-(
=> Add PL/SQL to active languages

lib/app/views/styleguide/_example.erb
Noticed http://exercism.io/styleguide wasn't loading. I think this fixes it!
=> Fixed styleguide page load

lib/app/helpers/markdown.rb, lib/app/views/code/random.erb, lib/app/views/submissions/current_submission.erb, lib/exercism/markdown.rb
In an attempt to fix elixir code on the submission page ended up also fixing it for Perl, OCaml and C++.
=> Map file extensions to language names for Rouge

lib/app/views/looks/index.erb
Fixes disable logic on next button
Adds conditional logic to only show pagination if necessary
=> Fix pagination on 'looks/index' - Fixes #2205

README.md
Added more detail around using MailCatcher.
=> Updated MailCatcher notes

lib/app/views/application/footer/sponsors.erb
Matched link text to SendGrid branding.
=> Updated SendGrid link text

lib/app/views/auth/please_login.erb
Tiny change. Sorry for being the capitalization police! :cop: :oncoming_police_car:
=> Changed GitHub text

lib/app/views/application/footer/links.erb
=>  Removed Getting started with Ruby link from footer

lib/app/views/site/conversations.erb
Set the label color to red. Let me know if you prefer a different color there.
=> Fixed styling bug. Fixes #2256

lib/services/notification_message.rb
=> Exclude notifications from pending submissions in email.

lib/app/views/submissions/submit_comment.erb
@kytrinyx 
This is just using JS for everything. I'm not sure where this code should go, or if it's worth keeping. More or less a prototype to see if it would work.
I had to use a timeout at one point, I need to look into it more, but I think it is related to the angular stuff going on.
=> Keeping Nitpick Around

CONTRIBUTING.md
Because trying to answer the question of what frameworks the Exercism website uses was the reason I even opened `CONTRIBUTING.md`.
=> Mention frameworks used in CONTRIBUTING.md

test/app/helpers/site_title_helper_test.rb
I have tried to fix a test here. Though, I haven't really worked with Sinatra/Minitest before and would like some scrutiny of my code.
- I have renamed helper method to setup as I found mentioned in the minitest docs and a lot of other places. Also, I am now testing the assertions against an instance of helper object.
- I am using indentation to for the argument to helper.extend instead of brackets.
=> Fix site_title_helper_test

lib/api/routes/iterations.rb, test/api/iterations_test.rb
Some minor refactorization of  API `Iterations` class as discussed in #2282.
=> Minor refactorization of 'api/routes/iterations.rb' and it's test

lib/app/views/layout.erb, lib/app/views/styleguide.erb
A quick fix to https://github.com/exercism/exercism.io/issues/2300
=> add og:title & og:image to lib/app/layout.erb & lib/app/styleguide.erb

lib/app/views/application/nav/notifications.erb
Just a small change to make the notification badge look better
=> Change notification badge style

.gitignore, client/README.md, client/app/components/comment_box/comment_box.html, client/app/components/comment_box/comment_box.sass, client/app/components/comment_box/comment_box_directive.js, client/app/components/comment_box/comment_box_directive.spec.js, client/app/components/comment_box/index.js, client/app/main.js, client/bower.json, client/e2e/dashboard/dashboard.spec.js, client/gulpfile.js, client/karma.conf.js, client/package.json, client/protractor.config.js, client/tasks/build.js, client/tasks/clean.js, client/tasks/e2e.js, client/tasks/test.js, client/tasks/watch.js, client/webpack.config.js, client/webpack.config.test.js, lib/app/views/application/_footer.erb
Incomplete and bit messy docs for new client. Anyway still should make many things discussed in #2296 much clearer.
=> Docs and foundations of new client

client/README.md
Just going through the new /client README and saw a couple of quick fixers. Feel free to take none/any/all, cheers.
#2163
=> Minor /client README updates

README.md
The Rakefile makes various assumptions on how to connect to the database
for setup. This note explains how to set various database connection
parameters that might need to be set in order to successfully create
everything.
=> Add note about database setup

.travis.yml
(Forgot this in the previous commits where database.yml was renamed)
=> Travis CI: Copy database file before running tests

.travis.yml
Travis recently introduced their new container environment and it’s way faster :clock1:
=> Enable Travis containerized builds

README.md
For retina devices it makes **all** the difference
=> Use svg badges in readme

Gemfile.lock, lib/app/routes/teams.rb, lib/exercism/team.rb, lib/exercism/team_membership.rb, test/exercism/team_test.rb
as a club manager, when i destroy a club 
all of the team's memberships are also destroyed.
=> deletes team memberships when deleting a team #2411

lib/app/views/site/getting-started.erb
Not a large change, but just enough to highlight the iterative process.
re: #2090
=> Highlight the iterative process

frontend/app/js/script.js, lib/app/presenters/profile.rb, lib/app/public/js/app.js, lib/app/views/account/show.erb, lib/app/views/user/show.erb, test/app/presenters/profile_test.rb
=> Correct all instances of 'sumbission' to 'submission'

lib/app.rb, lib/app/routes/teams.rb
so it does not break when Sessions is placed below it in lib/app.rb
=> Add please_login call to all methods in Teams

lib/app/helpers/markdown.rb
=> Get syntax highlighting working for elisp.

lib/app/views/account/show.erb
=> Fix invitation styling

test/app/presenters/tracks_test.rb
Edit tracks test to use sample data instead of pulling from API, which was making the tests fail when tracks_test.rb was run on its own.
=> tracks_test.rb tests methods from sample data now

lib/app/views/application/_nav.erb
=> Add link to dashboard in navbar

lib/app/public/js/app.js, lib/app/views/site/index.erb
Hi @kytrinyx, 
Sped up tooltip. Thought of changing the background color, then noticed all the other tooltips on site have a black background.
cc: @sguermond
=> Why Github blurb tooltip

lib/app/routes/main.rb, lib/app/views/dashboard.erb
- Link to see all if ongoing exercises > 5
- Added tab spacing for visibility
- Added <section class=page-header> to greeting
- Removed commented code in lib/app/routes/main.rb
Uses feedback from #2484
=> Limit exercises in dashboard to first 5

lib/app/presenters/profile.rb, lib/app/views/user/_exercises_table.erb, lib/app/views/user/show.erb
- change order of exercises and languages
- resize current/completed columns to match
- make it easier to see which exercises can be nitpicked
- add star next to exercise name
- add info message at top of page
=> Enhance user profile page

lib/app/helpers/markdown.rb
Fixes #2241 
Built on top of #2458 (see #2454 for details)
=> Add syntax-highlighting for plsql.

lib/app/routes/github_callback.rb, lib/app/routes/main.rb, lib/app/routes/onboarding_steps.rb, lib/app/routes/teams.rb, lib/app/routes/user.rb, lib/app/views/application/_nav.erb
Hi @kytrinyx,
Now the logged-in users can see the homepage when they click on the exercism logo at the top left of the page.
Did you want logged in users to be directed to their dashboard when they log in? Or stay on the homepage?
cc: @sguermond
=> Logged in users can see the homepage

lib/app/views/teams/member_submissions.erb, lib/app/views/teams/show.erb
=> Limit team member exercises to 5

lib/app/views/site/index.erb
=> Replace Github login with link to dashboard for logged in users

lib/app/views/account/show.erb, test/acceptance/team_test.rb
Deal with the tabs issue #2469 by removing them entirely.
=> Remove tabs from account page

lib/app/views/dashboard.erb
Makes support channels more visible.
=> Link to Gitter support chat and new Github issue on dashboard

lib/app/views/application/_nav.erb, lib/app/views/application/nav/notifications.erb, lib/app/views/notifications/index.erb
Notifications in the navbar replaced with icon for space
Notification stream reformatted to better display activity: who did what, and how is it relevant to me?
=> Clean up notification formatting

db/migrate/201509151000_create_five_a_day_counts_table.rb, lib/app/routes/comments.rb, lib/app/views/application/_nav.erb, lib/app/views/application/nav/five_a_day.erb, lib/exercism.rb, lib/exercism/comment.rb, lib/exercism/five_a_day_count.rb, lib/exercism/user.rb, test/exercism/comment_test.rb, test/exercism/user_test.rb
Create FiveADayCounts class.
Create database migration to add the five_a_day_counts table.
Add SQL query to find five exercises by five unique users which don't belong to current user, current user  has not commented on, are not stale, user has access to exercises, and exercises are arranged in ascending order by number of comments.
Add dropdown menu that displays exercises.
Add number to menu bar which displays comments to be made that day that decreases as comments are made.
=> Five a Day Suggestions Feature

lib/exercism/user.rb
Add conditional to filter for 'hello-world' exercise in all languages(tracks).
Solves #2559
=> Solves Exclude 'hello-world' from five a day feature #2559

lib/app/routes/languages.rb, lib/app/views/languages/_header.erb, lib/app/views/languages/in_progress.erb, lib/app/views/languages/languages.erb, lib/app/views/languages/not_implemented.erb
I saw that the view was mostly handling what content to render instead of the controller. I broke down several pieces of markup in the `languages.erb` file into separate files. I'd also like to test this, could you point me in the right way? Thanks.
=> Refactor languages views

lib/app/routes/languages.rb, lib/app/views/languages/_docs.erb, lib/app/views/languages/_getting_started.erb, lib/app/views/languages/first_problem.erb, lib/app/views/languages/languages.erb, lib/exercism/user.rb
The "Available Exercises" section will be shown if the user has fetched their first problem. While, the "Fetch your first exercise" section will be shown if the user hasn't fetched their first problem.
Do I still need to add tests for this? Thanks!
#2604
=> Show / hide "Available Exercises" section on a language page

lib/app/views/site/index.erb
Issue: #2604 
@kytrinyx I removed the `demo` mention in the homepage I browse for more mention about de the demo feature, but haven't found another. If there are more as you said we will find them.
=> Remove demo version from homepage

CONTRIBUTING.md, bin/setup, lib/tasks/db.rake, lib/tasks/seed.rake
Add a simple setup script (e.g. https://robots.thoughtbot.com/bin-setup) to make it quick and easy to get started developing the app.
=> Setup script

app/views/submissions/header.erb
Closes https://github.com/exercism/todo/issues/173.
=> Add author avatar to code page

CODE_OF_CONDUCT.md
Exercism was using an older version of the Contributor Covenant so I thought I'd update it!
I had to leave [INSERT EMAIL ADDRESS] in because I don't know which email you wish to use. Happy to update if you can give me that info!
Have a wonderful day :sparkles:.
=> Update COC to latest Contributor Covenant version

app/helpers/syntax.rb, lib/exercism/comment.rb, test/app/helpers/syntax_test.rb, test/app/submissions_test.rb
=> Wrap code and comments in ng-non-bindable to ignore angular

lib/exercism/user.rb, test/exercism/user_test.rb
=> #2666 Overwrite avatar URL when loading user from Github

db/migrate/201512072011_create_dailies.rb
=> Add dailies view

app/views/submissions/header.erb, app/views/submissions/iterations.erb, public/sass/layouts/submission.scss
=> Change completed to archived in submissions view

app/views/languages/index.erb
@kytrinyx . Show upcoming languages if at least the have one problem.
=> Show upcoming languages if at least one problem

app/views/languages/_block.erb, app/views/languages/index.erb
Issue: #2677 
@kytrinyx I don't have a wide screen to test this, but I downloaded a screen modifier and seems to look good. Could you have a look with your screen to see if its work.
Thanks. 
Let me know if don't work to change it.
=> Added more breakpoints for all languages page

CONTRIBUTING.md
=> Add note regarding Postgres.app command line tools

app/views/dashboard.erb
=> Show pretty language name in notifications area of dashboard

app/views/user/_exercises_table.erb
Non-americans will appreciate this :)
=> Use internationally recognizable programmer-friendly date format 📅

api/v1/routes/iterations.rb, lib/exercism/iteration.rb, lib/exercism/use_cases/attempt.rb, test/api/iterations_test.rb, test/exercism/use_cases/attempt_test.rb
Please review #2713 before merging this as it is based on that. 
This will allow us to comment when submitting an iteration. 
Fixes https://github.com/exercism/exercism.io/issues/2588 and will allow us to fulfill https://github.com/exercism/cli/issues/225
=> Submission comments

config.ru, scripts/console.rb, test/test_helper.rb
=> Fail when migrations are pending

app/views/site/_add_more.erb, app/views/site/cli.erb, app/views/site/help.erb
Also add links for creating an issue and submitting a pull request pointing to github help pages.
=> Create partial for add more sections on cli and help pages

app/routes/core.rb, app/views/application/_navbar.erb, test/x_helper.rb, x/track.rb
=> Refactor code for fetching active tracks using new API

app/routes/account.rb, lib/exercism/user.rb, test/exercism/user_test.rb
Fixes #2751 
@kytrinyx , let me know what you think!
=> Update acls when adding track mentor to user

lib/exercism/markdown.rb, test/exercism/markdown_test.rb
Possible patch for #2759 
@kytrinyx and @toolness,
Thoughts? I know this is less than ideal but... redcarpet doesn't support this yet (see my irb screenshots on issue).
I was thinking about opening a ticket for redcarpet too (and maybe trying out some C).
=> Add preprocess to patch redcarpet for lists

app/views/teams/manage.erb
=> Overide team update form post to put to conform with route

CONTRIBUTING.md
WIP. Not ready to merge just yet.
@kytrinyx , just curious what you think about this. Not really sure about the depth for each each section.
Do you think this is in the right direction? Do you have any tips? Any preliminary edits?
Currently, I'm missing the part on the XAPI (I honestly don't know much about it) and some misc sections (config, docs and public).
Thanks :D
=> Exercism.io Overview Docs

.travis.yml, Gemfile, Gemfile.lock
Testing Testing 1... 2... 3...
=> Test travis with commonmarker

app/views/user/_exercises_table.erb
=> Make delete column narrow

lib/exercism/homework.rb, test/exercism/homework_test.rb
#2804
@kytrinyx fixed status endpoint
=> Fix status endpoint, to show fetched exercises information

app/views/application/_navbar.erb
=> Get rid of dropdown for languages.

app/views/submissions/user_actions.erb
=> Clarify Delete button/Confirmation on exercise page.

Gemfile, Gemfile.lock
=> Locks the Rubocop version

app/routes/languages.rb, app/views/languages/language.erb, x/docs.rb, x/docs/launch.rb, x/docs/md/track/LAUNCH.md, x/docs/track.rb
Add basic information to explain how to help launch a new track.
Fixes #2820
=> Add launch help tab to new language tracks

app/helpers/fuzzy_time.rb, app/views/stream/_main.erb, test/app/helpers/fuzzy_time_test.rb
This PR is in reference to #2861
=> Tweak human-friendly date display

app/views/dashboard.erb
Modify dashboard for users with no submissions.
=> [Finishes #2856] - Modify dashboard for users with no submissions

app/views/user/_exercises_table.erb, lib/exercism/user_exercise.rb
=> bugfix - display the latest iteration when possible

app/views/submissions/show.erb
=> Link to relevant activity stream from submission page

app/views/user/show.erb
=> On private page, "More Languages" button doesn't work

x/docs/md/cli/mac.md
This provides some basic instruction for how to find out if homebrew is
installed, for someone that may not be familiar with a terminal in any way.
=> WIP: How to decide which install method for OSX

app/routes/languages.rb, x/docs/launch.rb, x/docs/md/track/LAUNCH.md, x/track.rb
=> link directly to the issue on LAUNCH.md.

app/presenters/profile.rb, app/routes/solutions.rb, app/views/submissions/see_other_implementations.erb, app/views/submissions/show.erb, app/views/user/_archived_exercises_table.erb, app/views/user/_exercises_table.erb, lib/exercism/guest.rb, lib/exercism/user.rb, test/app/presenters/profile_test.rb
checks if user has access to solutions before renders the link.
fixes #2894
=> bugfix link to see other implementations of x

app/views/user/show.erb
=> Only display to the owner of the profile

app/views/site/about.erb
Add's Katrina's talks to the About page.
In reference to: https://github.com/exercism/exercism.io/issues/2953
=> Add talk references to about page

app/views/languages/language.erb
Moved "Installing ..." above "Running the Tests"
=> Rearranged left menu

x/docs/md/intro/getting-started.md
- added how to submit multiple files for languages that have headers. 
- I am not sure if this should be broken into its own section because then we could explain how to submit test files if that is desired.
=> Added how to submit multiple files for problem

x/docs/md/cli/overview.md
=> Adding instructions for submitting solutions

x/docs/md/cli/overview.md
Removing go get information as per #2922
=> removing go get information

app/routes/exercises.rb, app/views/user/_exercises_table.erb, frontend/app/js/app.coffee, public/js/app.js, test/app/exercises_test.rb
[Bulk archive of submission](https://github.com/exercism/exercism.io/issues/2971)
- Remove form action
- Bind listener to submit buttons and dynamically add the action back
- If it breaks
- Everything else should behave in the same way
- Also added additional specs for bulk delete
=> 2971: Bulk archive of submission

app/views/site/how_it_works_newbie.erb, x/docs/md/intro/local-remote.md
Updates to add information about submitting incomplete code as per https://github.com/exercism/discussions/issues/54
=> Incomplete code

lib/exercism/user_finished_tracks.rb, test/exercism/user_finished_tracks_test.rb
=> User finished tracks should consider tracks that are >100% complete

app/routes/core.rb, app/views/errors/internal.erb
Only show the message that Bugsnag has been notified if Bugsnag *was* notified of the error.
=> Only show Bugsnag message if notification occurred

CONTRIBUTING.md
* Ask for building/compiling before commiting to make sure changes are
added to compiled files.
* Use `--production` flag with `compass build` so that compass uses
production defaults as given here: http://compass-style.org/help/
=> Clarify frontend development instructions in CONTRIBUTING.md file

db/migrate/201609102229_create_team_membership_requests_table.rb
This table will be the first step in implementing the team membership
request feature. Refer to [this PR](https://github.com/exercism/exercism.io/pull/3092).
=> Add team_membership_requests table.

app/views/submissions/show.erb
Fixes issue #3010. 
Please let me know if there's more styling you'd like to see. If so, I would love some guidance on how to do that.
=> Fix my solution

app/views/application/footer/sponsors.erb
Bugsnag's blog has been moved, so this commit updates the sponsors link.
=> Fix Bugsnag link

lib/exercism/track_stream_filters.rb, test/exercism/track_stream_filters_test.rb
The "my solutions" filter which was added to the sidebar of the track activity stream in #3115 was not showing the "unread" badge count, even if there were unread items there.
This would mean that someone who is looking at the activity stream for a track would not know that they've received feedback, and so they might not go look at their "my solutions" stream.
Fixes #3132
@bernardoamc would you have time to take a look at this code and make sure I'm thinking this through correctly?
/cc @ramyaravindranath since you implemented the original filter
=> Fix bug in viewer filter

lib/exercism/track_stream.rb, test/exercism/track_stream_test.rb
**Note: this is a follow-on pull request building on four PRs (#3141, #3142, and #3131 which are separate, and  #3143 which builds on #3131). All of these should be merged before this one. This will make it easier to review, as it will contain significantly fewer changes.**
The earlier PRs add a watermarks table to the database, and use both the watermark records and the view records to set the read/unread state on the streams.
Now that all that prior functionality is in place, we can start using the watermarks table for the "mark all as read" feature, rather than creating individual view records for every single exercise in the stream.
This should alleviate some of the pressure on our database, which is quickly approaching the 10 million row limit.
See …
=> [WIP] Reimplement mark all as read using watermarks

bin/setup
I think this would get close or fix #3145 but... I keep getting hung up on jshint warnings when running `npm install`. I seem to get this normally (I usually just `--force` like it tells me too).
=> Add frontend build tasks and lineman install to bin/setup

app/views/languages/language.erb
Fixes #3149
This PR fixes the bug referenced in the issue #3149.
Currently the bug is caused by the logic which controls when to render the launch page. 
This PR fixes the logic error by adding conditions to determine when to render the launch page.
=> Upcoming and planned languages pages improvement

lib/exercism/stream.rb
This helps with the refactoring in #3164
/cc @nickborromeo @mhelmetag @bernardoamc
=> Swap trackler into the activity streams

app/views/user/_track_progress.erb, lib/exercism/user_finished_tracks.rb, lib/exercism/user_tracks_summary.rb, test/exercism/user_finished_tracks_test.rb, test/exercism/user_tracks_summary_test.rb
This helps with the refactoring in #3164
All of the changes have to do with the "progress" tracking that we show on the profile page.
/cc @nickborromeo @mhelmetag @bernardoamc
=> Swap trackler into the user profile

CONTRIBUTING.md
Just a typo and trailing whitespace...
=> Fix typo and trim trailing whitespace

app/views/application/nav/account.erb
Just adding teams to the drop down, I assume there will be more to this with managed teams and there is probably some ui changes that still need to be made. 
Thanks for all the help and pairing @blackcathacker 🙌 
This is a WIP from :zap: from [Fullstack LA](https://github.com/fullstackla) 🎉 
fixes #3228
=> add in teams to the account drop down

app/views/application/_navbar.erb, app/views/application/nav/teams.erb
a slight revision ontop #3229 to make the team dropdown look like the screenshot below
Sorry @kytrinyx for the confusion here is the last bit of code to make that screenshot work. LMK if there is any other changes that need to be done 😄
=> add in new dropdown for teams tab

lib/tasks/db.rake
@kytrinyx , just refactoring the db setup so that we don't try to make a new db and fail if it already exists.
=> Don't try setting up db if it already exists

x/docs/md/cli/windows.md
carrying this over from https://github.com/exercism/exercism.io/pull/3218
=> update formatting of cli windows.md

lib/exercism/user_exercise.rb, test/exercism/user_exercise_test.rb
Make the dashboard view show 'Your exercises in progress' that are
sorted by the most recent first.
Resolves #3246
=> Sort exercises by most recent

app/views/submissions/current_submission.erb, frontend/app/js/clipboardcopy.js, frontend/app/js/script.js, public/sass/layouts/submission.scss
Each file in a multiple file submission will have a button to
copy the text to the clipboard and a button to expand/shrink
the code text window.
Addresses #3276
=>  Add copy/expand buttons to multi file submissions

app/views/teams/list.erb, public/sass/layouts/team_search_page.scss
Screenshot for the https://github.com/exercism/exercism.io/issues/3274
=> Add `Create Team` button on /teams page

app/views/submissions/comment.erb, app/views/submissions/nit.erb, frontend/app/js/script.js
- Added a reply button to each nit box. On clicking the button the comment area is populated with quoted text
- Currently, I am setting a data attribute on the comment box with the raw nit content to avoid an AJAX call and am then using jQuery to format the text and set it in the comment textarea.
=> Added reply button to quote a nit

test/exercism/comment_test.rb
I think this should fix #3342.
=> assert array contents, indifferent of ordering

docs/maintaining-a-track.md
As discussed in exercism/discussions#115, the important bit is getting a review, not who merges the PR.
=> Tweak "PR" language for precision

docs/setting-up-local-development.md
- be explicit about versions of dependencies.
- rely on package managers for installing software.
- clarify use of Docker/Vagrant
- switch use the imperative consistently in the section titles as these are instructions.
- clarify OAuth configuration steps.
=> Tweak Development Setup Instructions

app/routes/teams.rb
This fixes #3363 .
I didn't add any acceptance test because pagination does not seem to not be tested on other pages.
Feel free to tell me if tests are necessary and I'll add them.
=> Fix pagination stream routes

CONTRIBUTING.md, app/views/languages/repositories.erb, docs/overview-architecture.md, docs/overview-of-exercism.md, test/app/languages_test.rb
This is a very high-level overview of the project, intended as a starting point
for people who think they might want to contribute.
[View rendered file](https://github.com/exercism/exercism.io/blob/docs-overview/docs/overview-of-exercism.md)
If we merge this, we will need to update #3253 to request that the filename used to describe the architecture should be `docs/overview-architecture.md`.
I also updated the /repositories page to remove some of the overlap with this new page.
**before**
**after** (notice that it links to the new documentation)
=> Write an overview of Exercism

Gemfile, Gemfile.lock, app/helpers/submission.rb, app/views/submissions/current_submission.erb, frontend/app/js/diff.js, frontend/app/js/preview.js, frontend/app/js/script.js, frontend/vendor/js/diff.min.js, public/sass/base/themes/exercism.scss, public/sass/layouts/submission.scss
When viewing a submission with multiple iterations, click the diff
button to see a side by side diff comparison between two iterations.
Refer: #3307 
This is a carry of #3331
@Motardo would you please review this to make sure it looks like you expect it to?
=> Add diff view of other iterations

app/views/site/how_it_works_newbie.erb
This carries the work started in #3302.
=> Simplify and clarify the CLI CTA for newbies 

app/helpers.rb, app/helpers/notification_by_language.rb, app/routes/core.rb, app/views/notifications/index.erb, test/app/helpers/notification_by_language_test.rb
This PR is a address issue #3140 and is a continuation of PR #3207.
I was browsing the issues and came across this, would be nice to see to fruition.  Please let me know if there is anything else needed.  Just jumping in here I very well may have missed something. Thanks!
=> Carry 3207

frontend/app/js/app.coffee
1. Being asked "what _could_ you learn" made me respond with indifference. Being asked "what _did_ you learn" set an expectation that I should have learned and made me think about it.
2. Ensure the new-prompt button gives a different one: random means the same one can be chosen as a replacement.
=> Two tweaks for prompts

x/docs/md/cli/linux.md
Update the link as it points to the old version.
=> Update Linux CLI releases link

db/migrate/201704142144_opt_out_the_bot.rb
=> Prevent Rikki bot from affecting behavior study

app/views/site/cli.erb
The page was losing padding when resized.
Closes #3463
=> Update layout of CLI pages

.github/stale.yml
Fixes: #3449 
Default configuration, due to empty file.
=> Stale Configuration for Probot

CONTRIBUTING.md
1. Remove extra bullets.
2. Fix `I would like to help` section table.
=> Fix CONTRIBUTING.md view.

docs/setting-up-local-development.md
Update: Fixed my repository, branches are fixed so only one document and one file changed is shown up in a single pull request.
Originally this was to add instructions for getting Ruby-Build off of github after having trouble using the apt-get version.
Now it includes everything I changed in the setting-up-local-development.md file because I replaced getting Ruby-Build off of github with instructions for WSL itself.
=> Add Windows Subsystem for Linux troubleshooting steps to setting-up-local-development.md

Gemfile, Gemfile.lock
Upgrade bugsnag, should resolve #3469
=> Upgrade bugsnag, should resolve #3469

app/views/layout.erb, public/sass/base/components/main.scss
Fixes #3465, picked up @arumoy-shome’s work done in #3491.
Preview here: https://drive.google.com/file/d/0B6BKR27AYAAddzI2dThGYUtjRFU/view?usp=sharing (.webm file recorded by Awesome Screenshot for Chrome).
=> Make the footer sticky when necessary

docs/the-contribution-workflow.md
The documentation that referred to this is now referring to the open issue.
=> Delete documentation stub

app/routes/contribute.rb
This is a refactoring to support our new and improved choices for terminology for the
Exercism project.
See https://github.com/exercism/discussions/issues/145
This is a step in the refactoring described in https://github.com/exercism/trackler/issues/40#issuecomment-305338776
=> Use trackler specifications in place of problems

CONTRIBUTING.md
=> Add deployment instructions in contributing doc

x/docs/md/cli/windows.md
Updated, Fixed the whole mess I made with my original pull request. I went ahead and included a separate branch, and these are the changes I made.
Least I learned more about Git while I was fixing everything. Thats a positive I guess.
Fixes #3466
=> Include Link to Windows installer

x/docs/md/track/CONTRIBUTE.md
Reference [java/#349](https://github.com/exercism/java/issues/349)
=> Point would be contributors towards good first patches

docker/README.md
Source: https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install
=> Docker for Windows supports Windows 10 Education

x/docs/md/track/CONTRIBUTE.md
Was going through the csharp track documentation and noticed this link currently points to a 404.
=> Update help file link for making a new exercise

lib/exercism/syntax_highlighter.rb
See https://github.com/exercism/cfml/issues/54
=> Add mapping so CFML gets proper highlighting

x/docs/md/cli/linux.md
Added Nix/NixOS option of installation
=> Added additional package manager option

lib/exercism.rb, lib/exercism/activity_stream.rb, lib/exercism/activity_stream_filters.rb, lib/exercism/team_stream.rb, lib/exercism/team_stream_filters.rb, lib/exercism/track_stream.rb, lib/exercism/track_stream_filters.rb
Based on suggestions in https://github.com/exercism/exercism.io/issues/3676
=> DRY up Team and Track stream common code

app/routes/user_exercises.rb
Fix issue: https://github.com/exercism/exercism.io/issues/3633
=> Escape only the paths in the redirect param

app/routes/requests.rb
Tiny text update to the flash message when accepting a new user to a team to use the singular "is" instead of the plural "are"
=> Update request flash to use singular

x/docs/md/cli/linux.md
=> Added 'sudo' to install/uninstall instructions for Linux CLI

public/sass/base/components/banner.scss
https://github.com/exercism/exercism.io/issues/3781
=> Set z-index to avoid overlap

x/docs/md/track/TRY.md
`understood` should be `understand`.
=> TRY.md: minor grammatical improvement

README.md
remove extra '*' in italic link display in README.md
=> remove extra asterisk in README.md

tmp_freenode_verification
As discussed with Jeremy, registering Exercism with irc.freenode.net
Temporary verification file. Can be dropped once confirmed. Code is not sensitive.
=> Temporary FreeNode verification for registration

.github/workflows/stop-hacktoberfest-spam.yml
See https://github.com/exercism/website/pull/972
=> Add Hacktoberfest Spam Defence

.github/workflows/first-time-issue.yml
How did we not notice this at all?! :D
So many failures: https://github.com/exercism/exercism/actions
=> Fix first time greeting bot
